### ISSUE TITLE
A+B - 4 문제 재출시 오류

### ISSUE THREAD

**Issue by minpeter** [BaekjoonHub/BaekjoonHub#103]
**버그를 설명해주세요**</br>

```text
TypeError: Cannot read properties of undefined (reading 'forEach') at chrome-extension://ccammcjdkpgjmcpijpahlehmapgmphmk/scripts/storage.js:229:10 at async updateLocalStorageStats (chrome-extension://ccammcjdkpgjmcpijpahlehmapgmphmk/scripts/storage.js:228:3) at async versionUpdate (chrome-extension://ccammcjdkpgjmcpijpahlehmapgmphmk/scripts/baekjoon/baekjoon.js:125:17) at async beginUpload (chrome-extension://ccammcjdkpgjmcpijpahlehmapgmphmk/scripts/baekjoon/baekjoon.js:108:7) at async chrome-extension://ccammcjdkpgjmcpijpahlehmapgmphmk/scripts/baekjoon/baekjoon.js:82:9
```
![image](https://user-images.githubusercontent.com/62207008/161198641-10941b74-bc21-4d32-a4f2-f94d61e4c459.png)
제출중 창이 뜨고 얼마 있지 않아서 오류 발생

**재현 방법을 기술해주세요**</br>

`A+B - 4` 문제
python 3로 제출
edge 99버전
**스크린샷**</br>

![image](https://user-images.githubusercontent.com/62207008/161198641-10941b74-bc21-4d32-a4f2-f94d61e4c459.png)
![image](https://user-images.githubusercontent.com/62207008/161198753-700df1f1-0fd6-4db6-b2a5-5b3af1d8d999.png)

**추가 **</br>

**Comment by minpeter** [comment]
익스텐션 깃허브 인증이 안된거였습니다 :(

혹시 가능하시다면 인증이 풀린 경우 푸시알림으로 알려주면 좋겠습니다 👍🏼

**Comment by getCurrentThread** [comment]
#97 #98 이슈 대응된 버전입니다

**Comment by Haeeul** [comment]
동일한 에러를 issue에서 언급되지 않은 방법으로 해결하여
저와 같은 상황을 겪으시는 분들께 공유드리고자 가장 최근 이슈에 코멘트 남깁니다!

**Auth 오류 관련 issue에서 언급된 방법들** 
- 백준허브 익스텐션 재설치
- 백준허브 Auth 과정 재실행
- GitHub 토큰 만료 확인
- 레포 연결 확인

**필자 해결 방법**
- 비어있는 레포에 파일(README) 추가

저는 이미 언급된 방법들로는 해결되지 않았으며 레포는 **비어있는 상태**였습니다.
관련 issue에서 커밋 후에 작동하신다는 Nozzi2님의 말씀을 보고,
빈 상태인 것이 문제인가 싶어 **README 파일 하나를 추가**한 뒤에 실행해 보니 정상적으로 작동했습니다. 
에러가 발생하신 분들은 레포 확인 후에 한번 시도해 보세요..!

마지막으로 좋은 서비스 개발해 주신 백준허브 개발자님들 감사합니다!
