### ISSUE TITLE
프로그래머스의 신규 문제들이 unrated 등급으로 등록되는 문제

### ISSUE THREAD

**Issue by getCurrentThread** [BaekjoonHub/BaekjoonHub#107]
**버그를 설명해주세요**</br>

프로그래머스 문제들은 아래 링크의 소스코드에 levels로 저장되어 있는 목록에 의존되어 있어서
신규 연습 문제가 발생한 경우, unrated 등급으로만 등록이 되는 문제점이 있습니다.

이를 추가적으로 대응할 수 있는 방안이 필요 합니다.

https://github.com/BaekjoonHub/BaekjoonHub/blob/v.1.1.1/scripts/programmers/variables.js

**Comment by getCurrentThread** [comment]
오후 5:40 2022-07-07
프로그래머스 문의 시작.
> 안녕하세요. 백준허브(BaekjoonHub) 크롬 익스텐션 개발자 OOO 입니다.
> 
> 코딩 테스트 연습 문제들에 대해서 코드 에디터 또는 제출 페이지 내에도
> 문제에 대한 레벨 표시가 있었으면 좋겠습니다.
> 
> 별도로 외부 유입으로 들어오는 경우 문제 레벨에 대한 정보가 필요한데,
> 프로그래머스의 직접 링크로 들어오는 경우에는 레벨 정보가 표기가 되어 있지 않으므로
> 상위 페이지로 가지 않고서는 문제 레벨에 대한 파악이 현재는 어렵습니다.
> 
> 찬찬히 검토해주시고, 회신 부탁드리겠습니다.

**Comment by getCurrentThread** [comment]
회신. 2022년 7월 7일 17:57 GMT+9
> 안녕하세요, 프로그래머스 입니다. 
>  
> 우선 좋은 의견 주시어 진심으로 감사 드립니다. 
>  
> 말씀해 주신 내용은 담당부서로 전달하였으며 개선될 수 있는 부분이 있는지 적극 검토할 예정 입니다. 
> 해당 내용과 관련하여 확답 드릴 수 있는 내용이 확인되면 추가 안내 드리겠습니다.
>  
> 앞으로도 이용 중 불편하거나 개선되어야 할 점이 있다면 언제든 말씀해 주세요. 
>  
> 감사합니다. 
> 프로그래머스 드림

> 오후 5:40 2022-07-07 프로그래머스 문의 시작.
> 
> > 안녕하세요. 백준허브(BaekjoonHub) 크롬 익스텐션 개발자 OOO 입니다.
> > 코딩 테스트 연습 문제들에 대해서 코드 에디터 또는 제출 페이지 내에도
> > 문제에 대한 레벨 표시가 있었으면 좋겠습니다.
> > 별도로 외부 유입으로 들어오는 경우 문제 레벨에 대한 정보가 필요한데,
> > 프로그래머스의 직접 링크로 들어오는 경우에는 레벨 정보가 표기가 되어 있지 않으므로
> > 상위 페이지로 가지 않고서는 문제 레벨에 대한 파악이 현재는 어렵습니다.
> > 찬찬히 검토해주시고, 회신 부탁드리겠습니다.

**Comment by dev-redo** [comment]
안녕하세요.
혹시 해당 이슈를 크롤링으로 해결해도 괜찮다면 제가 기능을 구현해보고 싶습니다!

구현방법은 아래와 같습니다.
1. 프로그래머스 문제 정보 api를 이용해 문제 list를 크롤링한다.
2. 해당 작업을 github action을 이용해 매 시간마다 자동크롤링하게끔 한다.
3. 크롤링한 파일을 jsDelivr을 이용해 fetch할 수 있도록 한다.

프로그래머스 robots.txt를 확인해보면 문제 api는 allow하고 있습니다. 그래서 문제가 발생하지 않을거라 판단되나... 크롤링이 좀 그렇다면 참가하지 않겠습니다!

위의 구현방식은 제 리포지토리를 참고해주시면 될 듯 합니다. 한번 참고해보시고 괜찮으시다면 답장주시면 감사하겠습니다 :) 
리포지토리: https://github.com/dev-redo/programmers-problems

**Comment by getCurrentThread** [comment]
@whatasame 좋은 아이디어이지만, unrated 문제의 경우 매순간 사용자의 추가 입력을 
필요로 하게 되는 문제가 발생할 것으로 보여져요. 그리고 근본적인 해결책이 아닌 것으로 사려됩니다.
의견 감사합니다.

**Comment by ByeongsuPark** [comment]
이런 방법은 어떨까요?
<img width="616" alt="image" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/39683194/d8b5f4f2-0c25-4e54-b0fa-7a827fa46c4e" />  

코드를 제출하고 맞은 경우에는 저런 모달창이 뜹니댜. 문제 의견 제출하기에 들어가면
<img width="590" alt="image" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/39683194/1a1576f9-bbf4-4536-b9a0-4863f01c2548" />
위와 같이 질문에 레벨 정보가 포함되어 있는 걸 볼 수 있는데
해당 파일에 레벨 정보가 없는 경우에는 여기서 레벨 정보를 갖고 올 수도 있지 않을까요?
