### ISSUE TITLE
백준 대회 문제 업로드 에러

### ISSUE THREAD

**Issue by khcho0125** [BaekjoonHub/BaekjoonHub#108]
**버그를 설명해주세요**</br>

백준 대회 문제를 업로드 하려고 하면 Exception이 생깁니다.

**재현 방법을 기술해주세요**</br>

백준에서 해결한 대회 문제 업로드를 시도하면 진행 중에 에러가 발생하게 됩니다.
문제 번호가 숫자가 아닌 A, B, C 등 알파벳으로 명시된 문제만 json 에러가 생기게 됩니다.

**스크린샷**</br>

![image](https://user-images.githubusercontent.com/82090641/164013106-f15a17d5-5326-4456-aec4-1b2d5efc98f1.png)

![164013006-fd99d62e-f6ef-4a7c-a0ee-93e571bf5f2f](https://user-images.githubusercontent.com/82090641/164017521-5124f5a4-37f0-45d0-97b5-cad709cbd7ed.png)

위의 부분처럼 알파벳인 상황에 생깁니다.

![image](https://user-images.githubusercontent.com/82090641/164014129-a74b79bd-b90e-429f-af26-f1b018e6e163.png)

**Comment by getCurrentThread** [comment]
@khcho0125 깃허브와 같이 외부사이트에 업로드에 문제가 없는 연습문제에 속하는 문제 맞는지 확인 부탁드립니다.

**Comment by khcho0125** [comment]
@getCurrentThread 블로그에도 많이 올라오는 걸 보니 외부사이트에 올려도 문제없는 연습문제입니다.

**Comment by flaxinger** [comment]
관련하여 원인을 확인해보겠습니다.

다만 해당 에러가 대회 코드에 한해 발생하고 대회코드 특성상 적어도 대회가 진행되는 동안에는 깃허브에 푸시되어서는 안되기에 장기적으로는 (대회 진행 여부를 판단하여 푸시하기 보다) 대회가 끝난 이후에도 관련 코드의 푸시를 막을 것으로 생각하고 있습니다. 

현재는 별도 안내 없이 에러가 발생하므로 이를 처리하는 로직을 추가하는 쪽으로 수정이 될 것 같아 참고를 부탁드립니다.

**Comment by khcho0125** [comment]
답변 감사합니다 ❤️ 백준 허브 잘 사용하겠습니다.
