### ISSUE TITLE
우분투에서 백준허브 익스텐션 지원 추가 요청

### ISSUE THREAD

**Issue by junwoo-ctrl** [BaekjoonHub/BaekjoonHub#109]
**버그를 설명해주세요**</br>

**재현 방법을 기술해주세요**</br>

**스크린샷**</br>

**추가 **</br>

**Comment by flaxinger** [comment]
안녕하세요?

현재 익스텐션 테스팅은 윈도우, 맥을 기준으로만 하고 있으며 현재 형편상 우분투는 아직 지원 계획이 없습니다.

다만 어떤 에러가 발생하는지 스크린샷을 통해 첨부해주신다면 해결 가능한 문제인지 확인해보도록 하겠습니다.
