### ISSUE TITLE
백준에서 자바로 문제를 풀었는데, C언어로 깃허브에 업로드됩니다.

### ISSUE THREAD

**Issue by shimson7** [BaekjoonHub/BaekjoonHub#110]
**버그를 설명해주세요**</br>

**재현 방법을 기술해주세요**</br>

백준에서 연동이 잘 되었는지 확인하기 위해서 기본문제를 돌려봤는데 제가 풀지 않은 언어, 답변으로 깃허브에 업로드 되는 것을 발견했습니다.

**스크린샷**</br>

![image](https://user-images.githubusercontent.com/101376930/165471051-a433171f-7707-45c3-9c0d-1baacc79f72a.png)
![image](https://user-images.githubusercontent.com/101376930/165471109-e43057f1-0eb6-41d3-8259-9a290d77c763.png)

**추가 **</br>

**Comment by flaxinger** [comment]
안녕하세요, 
현재 백준허브는 최근 풀이가 아닌 최고 성능 코드를 깃허브에 업로드하고 있어 기존에 C로 문제를 해결하신 경험이 있다면 해당 풀이가 JAVA보다 우선될 확률이 높습니다. 관련하여서는 사용자 설명서에 기록되어 있습니다.

C로 문제를 해결하신 적이 없다면 답글 부탁드립니다.

**Comment by shimson7** [comment]
과거에 C언어로 잠깐 문제를 풀어본적이 있는데, 사용자 설명서에 JAVA로 변경하는 방법은 찾지 못하였습니다. 방법 알려주시면 감사하겠습니다!

**Comment by flaxinger** [comment]
현재는 언어를 특정하여 업로드할 수 있는 기능을  지원하고 있지 않습니다. 추후 지원할 예정이나 당장은 우선순위가 높지 않은 기능이어서 양해를 구합니다. 

다만 신규로 푸시는 문제에 대해서는 자바를 사용한다면 자바로 업로드될 것이어서 크게 걱정하지 않으셔도 됩니다.
