### ISSUE TITLE
사용 일시 중지를 만들어주세요.

### ISSUE THREAD

**Issue by ryuj-h** [BaekjoonHub/BaekjoonHub#113]
**해당 기능이 어떤 문제를 개선하나요?**</br>

현재 백준 사이트에서 어떤 코드를 냈었는지 리뷰하기 위해 클릭시 바로 깃에 올리는것 같습니다.
결과적으로 코드 확인도 못하고 바로 창이 닫혀서 아무 확인을 못하네요

**제안하고 싶은 기능을 설명해주세요**</br>

크롬에서 백준허브 ui 안에 토글으로 일시 중지 기능을 만들어 주시면 좋을 것 같습니다. 

**직접 PR 여부**</br>

NO

**Comment by getCurrentThread** [comment]
개인 일정으로 바빠 늦게 나마 답변 드립니다.

백준허브에서 동작하는 과정에  발생하는 **소스코드 페이지**는 
기존 제출 결과에서 **가장 결과가 좋은 소스코드**를 제출하기 위한 동작으로 
자동으로 닫히도록 의도한 것이 맞습니다.

이는 사용자가 직접 링크로 접근했을 때와 다른 url 주소를 가지고 있으며,
사용자 분께서 직접 소스코드를 열람하시려면 결과 테이블 페이지에서 제출한 소스코드로 들어가시는 것과
동일한 페이지로 구성이 되어 있으므로, 해당 페이지를 열람하시는 것을 권장드립니다. 

결과 테이블에 접근할 시에 추가적인 페이지가 뜨지 않는 쪽으로 코드 변경 예정 중에 있으나, 
백준 사이트 내의 부하를 발생시킬 수 있어 이러한 형태로 유지 중이니 양해 부탁드립니다.

소스코드 제출 후, 또는 내 제출 탭에 들어가신 후에 결과 테이블에서 **언어** 열에서 링크를 누르시면 확인하실 수 있습니다.

**Comment by getCurrentThread** [comment]
해당 이슈는 24시간 후 닫도록 하겠습니다. :)
