### ISSUE TITLE
백준에서 node.js 풀이 업로드 에러가 발생합니다.

### ISSUE THREAD

**Issue by dev-redo** [BaekjoonHub/BaekjoonHub#115]
**버그를 설명해주세요**</br>

백준에서 node.js 로 문제를 풀엇는데 업로드 에러가 발생하였습니다.

<br>

**재현 방법을 기술해주세요**</br>

안녕하세요. 개발해주신 백준허브 익스텐션을 잘 사용하고 있는 유저입니다.
이번에 node.js로 백준의 "수 고르기" 문제를 풀고 제출을 했는데 업로드 오류가 발생하였습니다.
그래서 혹시나 하여 이전에 node.js로 푼 문제 몇 개를 다시 제출해보았는데(해당 문제들을 풀 당시에는 익스텐션이 잘 작동해 깃허브 리포에 잘 올라갔습니다.)  전부 업로드 문제가 발생하였습니다.

1. OS: win10 64비트
2. 브라우저 버전: 크롬 101.0.4951.54
3. 익스텐션 버전: 1.0.12
4. 플랫폼: 백준

<br>

**스크린샷**</br>

![1](https://user-images.githubusercontent.com/69149030/167373056-3e60f469-e08c-4b70-a49c-41501408504c.png)
![1](https://user-images.githubusercontent.com/69149030/167373235-66cdfe97-c005-452f-86e4-776303b9a80b.png)

**추가 **</br>

**Comment by getCurrentThread** [comment]
깃허브에 대한 토큰이 만료되었을 시에 발생하는 오류 입니다.
현재 소스코드에는 오류 예외처리가 반영되어 있으나, 
추가 업데이트 예정 중이라 즉시 적용하지 못하는 점. 양해 부탁드립니다. :)

+ #97 #98 이슈 대응된 버전입니다

**Comment by getCurrentThread** [comment]
해당 오류는 백준허브를 삭제한 후에 재설치 하시면 해소할 수 있으니, 다음 방법으로 해소해주시기 바랍니다.

**Comment by getCurrentThread** [comment]
24시간 후에 해당 이슈 닫도록 하겠습니다.
