### ISSUE TITLE
rust 언어로 제출시, 확장자명 undefined로 깃허브 동기화.

### ISSUE THREAD

**Issue by cothi** [BaekjoonHub/BaekjoonHub#118]
**버그를 설명해주세요**</br>
rust 언어로 제출시, 확장자명 undefined로 깃허브 동기화.

**재현 방법을 기술해주세요**</br>
1. rust 2021 백준 사이트로 제출 진행
2. 파일 동기화 확인, 확장자명 undefined로 동기화

**Comment by getCurrentThread** [comment]
#119 PR 완료 후 정상 적용될 예정입니다.
