### ISSUE TITLE
기능을 껐다 킬 수 있는 스위치를 만들어주세요.

### ISSUE THREAD

**Issue by getCurrentThread** [BaekjoonHub/BaekjoonHub#126]
**해당 기능이 어떤 문제를 개선하나요?**</br>
일일이 익스텐션을 비활성화 하면서 사용하기는 번거롭네요.
익스텐션에서 기능을 키고 끌 수 있는 토글 스위치를 만들어 주셨으면 좋겠습니다 :)

**제안하고 싶은 기능을 설명해주세요**</br>
![1](https://user-images.githubusercontent.com/31976959/176855647-ee8e3693-8764-433a-bd4b-1b8ce83c6453.gif)

**직접 PR 여부**</br>
NO

**Comment by fhdufhdu** [comment]
@getCurrentThread  @flaxinger 
저도 on/off 기능이 필요해서 직접 기능 제작했는데, PR 해도 될까요?

**Comment by flaxinger** [comment]
@all-contributers please add fhdufhdu for maintenance

**Comment by flaxinger** [comment]
https://github.com/all-contributors please add @fhdufhdu for maintenance

**Comment by flaxinger** [comment]
@all-contributors please add @fhdufhdu for maintenance

**Comment by flaxinger** [comment]
@all-contributors please add @fhdufhdu for code
