### ISSUE TITLE
프로그래머스 서브 도메인 변경에 따른 미동작 오류

### ISSUE THREAD

**Issue by keinetwork** [BaekjoonHub/BaekjoonHub#127]
**버그를 설명해주세요**</br>

https://school.programmers.co.kr/learn/courses/30/lessons/12977
프로그래머스 url이 바뀌고 문제 풀어도 커밋이 안돼요.

**재현 방법을 기술해주세요**</br>

https://school.programmers.co.kr/learn/courses/30/lessons/12977
문제 정답 제출하기

**스크린샷**</br>

**추가 **</br>

**Comment by getCurrentThread** [comment]
@keinetwork 안녕하세요. 백준허브 컨트리뷰터 입니다. 
해당 문제 확인하였으며 바로 픽스 진행하도록 하겠습니다. 

제보 감사드립니다. 👍

**Comment by getCurrentThread** [comment]
@all-contributors please add @keinetwork for question

**Comment by getCurrentThread** [comment]
웹스토어에 검토 요청하였습니다. manifest 변경 건이라 시간이 조금 걸릴 수 있습니다.
완료 후에 추가 코멘트 드리겠습니다. 감사합니다 :)
