### ISSUE TITLE
백준 새로운 답 제출 시 맨 처음 코드만 인스펙션 되는 창이 뜹니다.

### ISSUE THREAD

**Issue by Jeongeum** [BaekjoonHub/BaekjoonHub#138]
**버그를 설명해주세요**</br>

안녕하세요.
혹시나 중복 이슈/고치고 계시는 중이라면 죄송합니다. 이슈를 처음 작성해봐서 서툰 점이 많습니다.

백준에서 문제를 풀어 맞추고 이미 깃허브에 올라간 문제를 다른 방식으로 풀고 또 맞췄을 때, 맨 처음에 맞춘 답만 올라갑니다.
아니 실제로는 올라가지는 않고 인스펙션 창만 뜨다가 사라집니다. 
프로그래머스는 풀었던 문제를 다른 방식으로 풀어도 올라갔는데 백준은 오류가 생긴걸까요?

**스크린샷**</br>

![image](https://user-images.githubusercontent.com/77143425/185335132-6042ca06-2979-40b4-9392-a211899276ca.png)

네개 다 다른 코드인데 맨 밑 코드만 올라가려고 창이 뜨더라구요.
밑에 사진 보시면 맨 처음 풀었던 2개월 전의 코드만 올라가고 그 후의 코드들은 올라가지 않았어요..ㅜㅜ
가장 최근에 업데이트 시킨건 제가 직접 코드 수정한거에요.

![image](https://user-images.githubusercontent.com/77143425/185335543-47467507-6d20-463e-8417-581a145f7bd3.png)

**Comment by doxxx93** [comment]
안녕하세요. 답변드립니다. 사용된 메모리, 시간이 작은 코드가 푸시됩니다.
