### ISSUE TITLE
제출 후 완료되지 않는 버그입니다.

### ISSUE THREAD

**Issue by Orchemi** [BaekjoonHub/BaekjoonHub#139]
**버그를 설명해주세요**</br>
이전 노트북에서 잘 써서 바뀐 노트북에서도 쓰고 있는데, 이전 노트북에서는 지금도 잘 되고, 지금 노트북에서 안 되는 건 어떤 문제일까요? 설정 문제는 아닌 것 같은데 말이죠...

제출 후 완료되지 않는 버그입니다.
버그 리포트 전에 Nightly 버전을 깔아봤는데 연결해놓은 Repo에 등록되는 걸 알게 되었습니다.
다만 아직도 실패했다는 실패 모달이 뜨는 게 불편하네요...

```
TypeError: Cannot read properties of undefined (reading 'forEach') at chrome-extension://ccammcjdkpgjmcpijpahlehmapgmphmk/scripts/storage.js:229:10 at async updateLocalStorageStats (chrome-extension://ccammcjdkpgjmcpijpahlehmapgmphmk/scripts/storage.js:228:3) at async versionUpdate (chrome-extension://ccammcjdkpgjmcpijpahlehmapgmphmk/scripts/baekjoon/baekjoon.js:126:17) at async beginUpload (chrome-extension://ccammcjdkpgjmcpijpahlehmapgmphmk/scripts/baekjoon/baekjoon.js:109:7) at async chrome-extension://ccammcjdkpgjmcpijpahlehmapgmphmk/scripts/baekjoon/baekjoon.js:83:9
```

**재현 방법을 기술해주세요**</br>

Window / BeakjoounHub 1.1.8 버전 / 백준 / 모든 문제

**스크린샷**</br>

![image](https://user-images.githubusercontent.com/86189596/185752694-373604c4-f6b9-4272-a5f0-a27c1860b825.png)

**Comment by getCurrentThread** [comment]
@Orchemi 
안녕하세요. 백준허브 1.1.9 업데이트를 진행한 컨트리뷰터입니다.

Nightly 버전으로 테스트 해보셨다고 하셨는데, 
새로운 버전(1.1.9)에서는 별도로 창 이동이 없으며, 모달창이 뜨지 않게 되었습니다.

혹시 백준허브와 백준허브 Nightly를 같이 설치한 상태에서 테스트 진행해보진 않으셨는지요.

**Comment by getCurrentThread** [comment]
별도 응답이 없어 이슈 닫도록 하겠습니다.
