### ISSUE TITLE
제출한 시간에 대한 정보가 저장되면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by seogudwns** [BaekjoonHub/BaekjoonHub#141]
**해당 기능이 어떤 문제를 개선하나요?**</br>

백준허브를 처음 사용하는, 코딩테스트를 준비하는(혹은 즐기는) 사람에게 repository를 정리하는 것에 용이성을 줄 것 같습니다.

**제안하고 싶은 기능을 설명해주세요**</br>

제출하는 문제가 저장될 때 README.md 혹은 폴더명에 제출한 시간에 대한 정보가 같이 저장되면 좋을 것 같습니다.

- 폴더명에 저장되는 경우 폴더명  : (22.04.01 22:40:59)1000. A＋B
- README.md에 저장되는 경우(1000번 문제로 예시를 들었습니다.)

----

# [Bronze V] A+B - 1000 

[문제 링크](https://www.acmicpc.net/problem/1000) 

### 성능 요약

메모리: 30840 KB, 시간: 68 ms

### 제출일자 --> 추가되는 부분

22.04.01 22:40:59

### 분류

구현(implementation), 사칙연산(arithmetic), 수학(math)

### 문제 설명

<p>두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.</p>

### 입력 

 <p>첫째 줄에 A와 B가 주어진다. (0 < A, B < 10)</p>

### 출력 

 <p>첫째 줄에 A+B를 출력한다.</p>

----

어떻게 하면 좋을지에 대한 아이디어는 따로 가지고있질 않고, 백준의 내 제출에 들어갔을 때 제출한 시간 위에 커서를 올리면 정보가 나옵니다.(아래는 예시 사진)

![image](https://user-images.githubusercontent.com/38065726/192520113-68b4ffcf-f25e-4d71-a292-15a19524c661.png)

**직접 PR 여부**</br>

YES(직접 해보고 싶은데 일단 기약이 없습니다.(사이드 프로젝트가 끝난 후에 할 것 같아요.) 만약 누군가 구현을 한다면 NO!)

감사합니다.

**Comment by flaxinger** [comment]
별도로 스크레이핑할 필요 없이 푸시 시점의 시스템 시간을 사용하면 구현 가능할 것 같습니다.(전체 업로드는 필요할 것으로 보임)

다만, 현재 [백준허브는 효율성 기반으로 레포의 코드를 업데이트](https://github.com/BaekjoonHub/BaekjoonHub/blob/v.1.1.11/scripts/baekjoon/util.js#L65-L78)하고 있으며, 시간을 폴더명에 포함하기 시작하면 특정 문제의 기존 제출 내역을 트래킹하기 힘들어진다는 문제가 발생합니다.

혹시 이와 관련하여 의견 있으실까요?
