### ISSUE TITLE
동일문제 다른 코드 다시 제출시 반영이 안됩니다..

### ISSUE THREAD

**Issue by percyfrank** [BaekjoonHub/BaekjoonHub#142]
**버그를 설명해주세요**</br>

같은 문제를 다른 코드로 다시 제출시 반영이 안되는 문제가 생깁니다. 어떻게 해야하는지 알 수 있을까요?

**재현 방법을 기술해주세요**</br>

**스크린샷**</br>

**추가 **</br>

**Comment by doxxx93** [comment]
안녕하세요. 답변드립니다. 사용된 메모리, 시간이 적은 코드가 푸시됩니다.
