### ISSUE TITLE
확장 사용시 이미지 로딩 안됨

### ISSUE THREAD

**Issue by limecats0331** [BaekjoonHub/BaekjoonHub#145]
**버그를 설명해주세요**</br>
백준에서 확장이 켜져 있는 상태에서 이미지가 있는 문제에 들어가면
간혈적으로 이미지 로딩이 바로 되지 않고
여러번 새로고침 해야 이미지가 로딩되는 현상이 있습니다.

**재현 방법을 기술해주세요**</br>
mac, window 둘다 chrome 사용
백준 허브 로그인 + 백준 로그인 상태에서 이미지가 있는 문제에 들어가면
이미지 태그에 src가 생기지 않고 이미지 공간에 빈 이미지가 나옴

**스크린샷**</br>
<img width="1584" alt="스크린샷 2022-10-07 오전 10 47 59" src="https://user-images.githubusercontent.com/101141644/194449513-4747aaea-fa30-4e19-89e5-b861d468d1d5.png">

<img width="519" alt="스크린샷 2022-10-07 오전 10 52 07" src="https://user-images.githubusercontent.com/101141644/194449601-c2873b79-3e8b-4326-9735-29bec13c6ba5.png">

**추가 **</br>
한번 로딩됐던 문제는 로딩 잘되는 경우도 있음
확장 끄면 로딩 안되는 문제는 발생하지 않았음

**Comment by getCurrentThread** [comment]
안녕하세요. 백준허브 익스텐션 서브컨트리뷰터입니다.

백준허브에서 이미지 관련으로 로직이 있는 곳은 
소스코드 제출을 실행 한 후에 **결과 테이블 페이지 내**에서 밖에 진행되지 않습니다.
그 외에 비동기 파싱을 정상 수행하기 위해 xhr 리소스 타입 외에는 패킷을 건드리는 경우 외에는 없습니다.
그나마 가능성 있는 것이 해당 문제의 데이터를 임시 저장하기 위해 파싱 후 저장하는데 있어서
부하가 커서 이미지 로드하는데 사이드이팩트가 발생하였다? 정도의 추측이 있겠네요.

현실적으로 위의 상황은 발생하기 어려워서 추측컨데 백준 서버 내에 이미지 최대 요청 처리가 700ms로 제한되어 있으나,
서버 요청 과다, 네트워크나 브라우저 처리 속도 등의 여러 복합적인 문제로 인하여 이미지 처리가 안된 것으로 보여집니다.
(이미지가 한번 로드 되어 캐싱된 이후로는 잘 나오는 것도 이와 같은 상황으로 추측)

백준허브를 사용하지 않는 상황에서도 종종 이미지 몇개가 로드를 실패하는 상황이 벌어지곤 하는 관계로 
직접적으로 이 버그를 고치기는 쉽지 않을 것 같습니다.

추가 기능으로 이미지를 다시 불러오도록 img 태그에 리로드를 걸어줄 순 있는데, 백준 서버 내에 어떤 부담이 더 가해질지 모르는 상황이라 조금 더 지켜봐야할 것으로 보여집니다.

이슈 남겨주셔서 감사합니다.

**Comment by getCurrentThread** [comment]
@limecats0331 
24시간 내에 추가 의견 없으시면 이슈 닫도록 하겠습니다.

**Comment by pjshwa** [comment]
저도 같은 문제 발생합니다. 더불어 확장으로 git 에 push 하였을 때도 이미지가 비어 있는 상태로 올라갑니다.
