### ISSUE TITLE
Level 0문제 

### ISSUE THREAD

**Issue by SANGDOLEE** [BaekjoonHub/BaekjoonHub#150]
**해당 기능이 어떤 문제를 개선하나요?**</br>

프로그래머스 기준으로 Level 마다 폴더생겨서 각 레벨에맞게 푸쉬되는거같은데
레벨0문제들이 최근에 생긴걸로 아는데, 이거는 폴더 이름이 다른게 생성되네요.

**제안하고 싶은 기능을 설명해주세요**</br>

**직접 PR 여부**</br>

**Comment by getCurrentThread** [comment]
지금 확인했네요. 오류 수정해서 올리도록 하겠습니다.

**Comment by getCurrentThread** [comment]
#[372cf95](https://github.com/BaekjoonHub/BaekjoonHub/commit/372cf9578c3fafbb457826d0654ccd14dc407202)
픽스 완료하였으며, 스토어에서 현재 검토중입니다.

**Comment by getCurrentThread** [comment]
이슈 닫겠습니다.
