### ISSUE TITLE
예전에 풀었던 문제 답 제출 시, 새로운 풀이가 업로드 되지 않고 예전에 풀었던 풀이가 업로드 됩니다.

### ISSUE THREAD

**Issue by isun-dev** [BaekjoonHub/BaekjoonHub#151]
**버그를 설명해주세요**</br>
예전에 파이썬으로 풀었던 문제가 있었습니다. 최근에 자바로 풀고 백준에서 제출하면, 깃허브에서는 예전 파이썬 코드로 올라가 있어, 다시 해당 commit을 수정해야 하는 버그가 있습니다. 

**재현 방법을 기술해주세요**</br>
OS: 윈도우, 맥OS 동일하게 발생
익스텐션 버전: 최신
플랫폼: 백준

**스크린샷**</br>
1) 아래 이미지를 보시면 .py 에서 .java로 수정했습니다.
- .py는 제가 대략 1년전 작성했던 코드이고, .java는 이번에 새로 푼 문제 입니다.
- 소스 코드의 내용도 예전에 풀었던 걸로 commit되어 있어서 새로 푼 걸로 수정했습니다.

![image](https://user-images.githubusercontent.com/43905552/197429220-523ce2dc-a142-4c33-a971-bb92d5e6b0f2.png)

**Comment by getCurrentThread** [comment]
#142 이슈와 동일합니다.
[https://velog.io/@flaxinger/백준허브-사용-방법](https://velog.io/@flaxinger/%EB%B0%B1%EC%A4%80%ED%97%88%EB%B8%8C-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95) 의 `4.3 최고 성능 코드 업로드`를 참고하시면, `1.0.2 버전`부터 최고 퍼포먼스에 해당되는 코드가 깃허브에 업로드 된다고 명시되어 있습니다.

**Comment by getCurrentThread** [comment]
이슈 닫습니다.

**Comment by flaxinger** [comment]
해당 이슈 관련 작업이 예정되어 있었으나 현재 미루어지고 있습니다. 신규 로직 적용 후 다시 공지 드리겠습니다.
