### ISSUE TITLE
업로드 시작 시 백준 사이트에서 PATCH를 막는 CORS 오류

### ISSUE THREAD

**Issue by KangHyojin1401** [BaekjoonHub/BaekjoonHub#157]
**버그를 설명해주세요**</br>

![image](https://user-images.githubusercontent.com/67770370/205448423-98a92ed9-a9e4-4492-8037-e44dd96f8f08.png)
제출 완료 후 채점현황에서는위처럼 업로드 성공 이미지가 뜨는데요,
실제 레포에서는 뜨지 않는 문제가 있습니다.

<br>

**재현 방법을 기술해주세요**</br>

- OS: Window 11
- 익스텐션 버전: 백준허브(BaekjoonHub) 1.1.11
- 플랫폼: 백준
- 문제 종류: 일반
- 문제: 2178

<br>

**스크린샷**</br>

![오류난 라인](https://user-images.githubusercontent.com/67770370/205448657-3320f385-db89-4501-9a8e-f4108f9c0736.png)
![Cors에러](https://user-images.githubusercontent.com/67770370/205448666-b24f3003-a45d-4732-a9f0-5aeadb59fd37.png)

콘솔을 살펴보았더니 PATCH 메소드 자체가 불가능해서 생기는 오류라고 생각했습니다. 

<br>

**추가**</br>

**Comment by getCurrentThread** [comment]
재현이 어려운데 해당 문제 계속 발생하는지 확인 부탁드립니다.

**Comment by KangHyojin1401** [comment]
네, 매일 제출하고 있는데 항상 같은 문제가 발생합니다.

**Comment by flaxinger** [comment]
혹시 [이 이슈](https://variety82p.tistory.com/m/entry/%EB%B0%B1%EC%A4%80%ED%97%88%EB%B8%8C-%EC%97%85%EB%A1%9C%EB%93%9C-%EC%97%90%EB%9F%AC-%EC%9D%B4%EC%8A%88)랑 동일한지 확인 가능할까요?
