### ISSUE TITLE
업로드된 문제 directory를 삭제 후 재제출 했을 경우 레포에 업로드가 안 됩니다.

### ISSUE THREAD

**Issue by Seongho0503** [BaekjoonHub/BaekjoonHub#159]
- 확인했습니다.

**버그를 설명해주세요**</br>
- 안녕하세요. 유용한 확장 프로그램 만들어 주셔서 감사합니다. 백준에서 문제를 맞았을 때 등록된 레포에 문제 폴더가 업로드가 1회 진행되는 기능이 있습니다. 레포에 업로드된 해당 문제 폴더를 삭제하고  주석을 달아서 재 제출했는데 초록색 체크만 뜨고 해당 문제가 레포에 업로드 되지 않는 현상이 발생합니다. 문제를 한 번 제출하고 이것을 재출했는지 어디에  메타데이터를 보관하는지 궁금합니다. 또한 이미 답을 제출해서 레포에  등록되면 그 문제 폴더를 삭제하고 다시 답을 제출하면 현재 버전상 원래 다시 레포에 추가 되는 기능이 없는지 궁금합니다. 

**재현 방법을 기술해주세요**</br>

OS ; 윈도우10 문제 ; 백준

**Comment by 5onchangwoo** [comment]
저또한 같은 문제를 겪고있습니다 ㅠㅠ...
