### ISSUE TITLE
부분 성공 이슈

### ISSUE THREAD

**Issue by engus525** [BaekjoonHub/BaekjoonHub#160]
부분 성공을 받은 이후에 AC 처리를 받은 경우 갱신이 되지 않는 것같습니다! 
검토 부탁드립니다! 정말 감사드리고 파이팅입니다! 새해복 많이 받으세요! (20230119)

**Comment by flaxinger** [comment]
문제가 정확히 이해되지 않았는데, 아래 플로우로 이해하면 될까요?

부분 성공 -> 깃허브로 푸시 -> 전체 성공 -> 깃허브로 푸시되지 않음

더불어 문제 링크를 함께 주시면 재현하는 것에 도움이 될 것 같습니다.
