### ISSUE TITLE
swea 업로드 안되요

### ISSUE THREAD

**Issue by doraimong** [BaekjoonHub/BaekjoonHub#162]
swea 에서 올라가지 않네요
**버그를 설명해주세요**</br>

**재현 방법을 기술해주세요**</br>

**스크린샷**</br>

**추가 **</br>

**Comment by getCurrentThread** [comment]
SWEA에서 어떤 부분에 올라가지 않는지 확인 부탁드립니다.
- Solving Club 또는 모의로 등록된 문제는 제출이 되지 않는 것이 정상입니다 :)
