### ISSUE TITLE
백준 폴더 분류와 관련해서 제안 드립니다.

### ISSUE THREAD

**Issue by Koderpark** [BaekjoonHub/BaekjoonHub#163]
**해당 기능이 어떤 문제를 개선하나요?**</br>
백준 문제가 현재 solved.ac 티어 기준으로 폴더 분류가 되고 있는 것 같은데,
문제 난이도 기여의 변화로 문제의 난이도 티어가 바뀌는 경우에
(Ex : silver V 였던 문제가 Bronze I 로 격하됨 )
폴더 분류를 다시 해줘야 할 것 같습니다.

**제안하고 싶은 기능을 설명해주세요**</br>
문제의 티어가 바뀌었을 때
이를 반영해 readme 수정 및 해결한 문제의 디렉토리 이동
or
기존의 solved.ac 티어 기반 디렉토리 분류를
백준 문제번호 등의 다른 기준으로 분류하거나
둘 중 선택할 수 있게 하는 옵션의 제공

![image](https://user-images.githubusercontent.com/43494256/221759454-db21b851-9421-499e-97b1-266e35e0f9f7.png)
(Ex : 문제번호 앞 두자리로 문제를 분류해둔 제 레포입니다)

후자가 보다 깔끔한 방향이 될 것 같아서
이쪽으로 구현하는게 좋지 않나 싶습니다.

**직접 PR 여부**</br>
YES

**Comment by getCurrentThread** [comment]
https://github.com/BaekjoonHub/BaekjoonHub/issues/106 이슈와 동일하기에 이슈 닫도록 하겠습니다.
