### ISSUE TITLE
CORS 에러로 인한 백준 문제 업로드 불가 문제

### ISSUE THREAD

**Issue by taekto** [BaekjoonHub/BaekjoonHub#166]
**버그를 설명해주세요**</br>

잘 업로드 되었었는데 갑자기 업로드가 안됩니다..
**재현 방법을 기술해주세요**</br>

백준 2980, 10709, 2548 업로드가 안됩니다 ㅠㅠ
**![image](https://user-images.githubusercontent.com/110243496/222996334-3a5b3f84-8daf-40a4-bd58-9082c0a8dabc.png)
**</br>

**추가 **</br>

**Comment by taekto** [comment]
컴퓨터를 여러 대 사용하는데 그것 때문인가요?

**Comment by getCurrentThread** [comment]
현재 이슈 내용 확인중입니다.

**Comment by RyuJiChang** [comment]
저도 동일하게 작동하지 않습니다.
전반적으로 예전 문제를 수정하면서 테스트 할 때 빨간색 v표시가 뜨는 것은
더 좋지 못한 코드여서 그런가? 싶었지만 시간, 메모리 모두 좋은 코드 또한 빨간색 v표시가 뜨는 것을 보고
아 예전에 풀었던 문제라서 다시 등록되지 않는건가? 라는 생각을 했지만
몇몇 문제는 등록이 된 상태에서 어느 순간부터 빨간색으로 적용됩니다.

거기까지는 딱히 신경쓰지 않는 부분이라 괜찮은데
오늘자 출석을 위해 문제를 풀었는데
해당 문제조차 올라가지 않는 모습을 보고 조금 심각하다는 생각이 들었습니다.
![image](https://user-images.githubusercontent.com/104156381/222997757-367db9ca-2700-44d3-bd98-6368eab04811.png)

**Comment by RyuJiChang** [comment]
다른 에러 관련 글을 보니 아래와 같은 CORS문제인 것 같습니다.
![image](https://user-images.githubusercontent.com/104156381/222998390-b26a0ab9-f091-4f14-8a0d-27125ed5dbfb.png)

이 사진이 도움이 될지는 모르겠지만 혹시 몰라서 올려봅니다.

**Comment by getCurrentThread** [comment]
CORS 내역 확인 했습니다. 감사합니다.

**Comment by gnlenfn** [comment]
![image](https://user-images.githubusercontent.com/39958073/223039322-ffe6ba87-42aa-486b-a961-e7d0800fa4ae.png)

에러메세지는 조금 다릅니다만 프로그래머스에서도 CORS 문제가 있지 않나 싶습니다.
3/6 15:54 방금 시도했습니다

**Comment by likelasttime** [comment]
![image](https://user-images.githubusercontent.com/46569105/223092828-f0750287-d8c8-4c4b-b29e-abf2547716cc.png)
저도 안 되네요.

**Comment by Seona056** [comment]
저만 안되는줄 알았는데, 이슈가 있나보네요

**Comment by timber3** [comment]
https://ducks228.tistory.com/entry/%ED%81%AC%EB%A1%AC-%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80-cors-disableenable

임시방법인지는 잘 모르겠습니다..

일단 이 페이지 따라 해보니 업로드는 되는것 같습니다.

**Comment by sjMun09** [comment]
방법 알려주셔서 감사합니다!
하지만 저는 timber3 님께서 알려주신 방법으로 해보았는데도 안되네요 ㅜㅜ..

**Comment by wonholim** [comment]
감사합니다~

**Comment by sjMun09** [comment]
저도 이해하고, 해결했습니다 감사합니다~

**Comment by byeongs1** [comment]
저도 cors 오류로 인해 업데이트가 안됐는데 한 번 해결법 찾아보겠습니다

**Comment by yangjj94** [comment]
저도 같은 이슈가 있었는데 Moesif Origin & CORS Changer 설치하고 on 하니 커밋이 됩니다.

**Comment by YujunSun0** [comment]
감사합니다!!
