### ISSUE TITLE
백준 2480 정답에도 빨간색 체크가 나오고 업로드 되지 않습니다...

### ISSUE THREAD

**Issue by Choi-HyunHo** [BaekjoonHub/BaekjoonHub#167]
잘 업로드 되었었는데 갑자기 업로드가 안됩니다..

백준 2480 업로드가 안됩니다
![image](https://user-images.githubusercontent.com/87301268/222998328-2a9a2183-d1b0-4f4f-98ab-adc04ef1208f.png)

**Comment by Choi-HyunHo** [comment]
![image](https://user-images.githubusercontent.com/87301268/222998729-64b53b78-0a55-4f89-a419-5da5a6130dc1.png)

**Comment by RyuJiChang** [comment]
오늘 오전 4시~5시에 오류가 발생한 것 같습니다.
연달아 예전 문제 수정 작업중이었는데 제일 최근 커밋이 6시간 전이 찍혀있습니다.
그 뒤로도 대략 7~8문제가 빨간색 처리되었습니다.

**Comment by sju3358** [comment]
![image](https://user-images.githubusercontent.com/44466109/222999233-db098bc6-fb8c-4ac3-95fc-8f5934bd1620.png)
저도 같은 문제 발생합니다

**Comment by sju3358** [comment]
![image](https://user-images.githubusercontent.com/44466109/222999391-30115e18-5ef3-4398-b129-fab4b10cbc5c.png)
이부분에서 error가 undefined라고 뜨네요

**Comment by sju3358** [comment]
![image](https://user-images.githubusercontent.com/44466109/222999624-5938fe59-ac4a-4cf3-806d-0b5083800571.png)
여기 replace가 undefined라고 뜨는데 무슨문제일까요..

**Comment by sju3358** [comment]
![image](https://user-images.githubusercontent.com/44466109/223000360-606782e5-b583-4a6f-ae64-d3f51c208ca1.png)
프로그래머스는 잘되는걸로 보아 백준사이트가 문제인거 같긴합니다

**Comment by sju3358** [comment]
![image](https://user-images.githubusercontent.com/44466109/223001052-7398f5b7-51a1-434a-b8dc-76a9f5d1da6b.png)
SWEA에서는 GITHUB 업로드 누르면 무한로딩 입니다

**Comment by Choi-HyunHo** [comment]
프로그래머스만 정상동작 인거같군요..

**Comment by RyuJiChang** [comment]
16번째 줄 findData 함수 내부에서 
data에 값을 구조분해 할당으로 추가하기 위해 
findProblemInfoAndSubmissionCode 함수를 사용하고
272번째 줄에 있는 findProblemInfoAndSubmissionCode 함수는 
다시 Promise.all로 함수들을 전부 처리해야 하는데 
그 중 일부인 263번째 줄에 있는 getSolvedACById 함수가 다시
240번째 줄에 있는 fetchSolvedACById 함수를 호출했고
fetchSolvedACById함수에서 아래의 get 요청을 보냈지만 CORS가 생긴 것으로 보입니다.
fetch(`https://solved.ac/api/v3/problem/show?problemId=${problemId}`, { method: 'GET' })

요약하면 replace가 되지 않는 이유는 level값이 들어가지 않았기 때문이고
그 값이 들어가지 않은 이유는 promise.all인데 그 중 하나의 내부 함수 하나에서 보낸 get요청이 터졌기 때문에 다른 값들도 보내지지 않았기 때문이라고 판단되네요

물론 그 요청 페이지를 들어가면 level을 포함하고 있기 때문에
결국 그 처리가 되지 않아서 문제인 것 같기는 합니다.

**Comment by getCurrentThread** [comment]
@Choi-HyunHo @RyuJiChang @sju3358 CORS 에러가 발생했음을 확인했습니다. 
boj-extended 익스텐션처럼 리스트를 줄여야할 것으로 보여서 시간이 조금 걸리는 점 양해부탁드립니다.

SWEA, 프로그래머스 사이트에서는 정상 동작합니다.

**Comment by sju3358** [comment]
@getCurrentThread 
SWEA 다른문제들은 정상적으로 업로드 되는데
2072. 홀수만 더하기 이문제만 정상적으로 업로드가 안되네요

**Comment by getCurrentThread** [comment]
@sju3358 기존에 제출했던 문제인 경우에 해당 URL에 대한 preflight 를 실시할 필요가 없다거나, 
백준허브 내의 캐시 데이터로 들어있다거나 하는 경우 정상적으로 업로드될 수 있습니다.
개별적인 문제에서 일어나는 상황이 아닌, 전체적인 상황이라고 보시면 됩니다.
