### ISSUE TITLE
CORS 에러로 인한 문제 업로드 불가

### ISSUE THREAD

**Issue by gnlenfn** [BaekjoonHub/BaekjoonHub#168]
**버그를 설명해주세요**</br>

다른 이슈들과 동일하게 CORS로 보이는데, 에러메세지가 좀 다른 것 같아 새로운 이슈로 올립니다.
(https://github.com/BaekjoonHub/BaekjoonHub/issues/166, https://github.com/BaekjoonHub/BaekjoonHub/issues/167)
**재현 방법을 기술해주세요**</br>

정답을 맞춘 문제가 업로드 되지 않고 빨간 체크로 나옵니다.
[가장 먼 노드](https://school.programmers.co.kr/learn/courses/30/lessons/49189)  
[샘터](https://www.acmicpc.net/problem/18513)  
이 두 문제에 대해 에러를 발견했고 제가 이전에 백준에서 풀었던 문제들도 빨간 체크로 나오는 것을 확인했습니다.

에러발견 후 익스텐션 재설치도 했기 때문에 최신 버전이라 생각합니다.

**스크린샷**</br>

프로그래머스
![image](https://user-images.githubusercontent.com/39958073/223040386-f70c309f-297e-4151-b9ab-b3da3a833bff.png)

백준
![image](https://user-images.githubusercontent.com/39958073/223040502-76ae7c33-3cb1-4692-a1dd-1a00616b4c16.png)

**추가 **</br>

**Comment by gnlenfn** [comment]
https://github.com/BaekjoonHub/BaekjoonHub/issues/157
참고로 위 이슈에서 언급하신대로 CORS를 끄면 동작하나 해봤지만 증상은 동일했습니다

**Comment by AdHoc2675** [comment]
저도 어제까지만 해도 잘 되었는데 오늘부터 안되네요

**Comment by S2econdBlue** [comment]
위 증상과 동일한 증상이 발생하고 있습니다.
cors extension을 통해 cors를 우회하면 몇 초 될 것 처럼 보이다가 cors 에러가 뜨네요.

**Comment by thwang26** [comment]
저도 동일한 이슈 발생합니다

**Comment by in-jun** [comment]
앗

**Comment by jyeonpark** [comment]
저도 동일 이슈 발생합니다ㅠㅠ cors확장프로그램 사용해도 안되네요

**Comment by gnlenfn** [comment]
원인이나 정확한 해결방안은 모르겠지만 CORS extension으로 임시해결하긴 했습니다.
extensino 설치 후 cors 껐다켰다하면서 새로고침 하니까 초록체크 뜨긴합니다

**Comment by thwang26** [comment]
https://github.com/BaekjoonHub/BaekjoonHub/issues/170
엣지 환경에서 위와같이 CORS extension 설치 후 문제 풀어보니까 작동됩니다
완전히 해결되기 전까지 임시방편으로 사용하시면 될 것 같아요
