### ISSUE TITLE
모든 제출 불가

### ISSUE THREAD

**Issue by goldsergeant** [BaekjoonHub/BaekjoonHub#169]
지금 제출이 안되고 빨간색 체크무늬만 떠요.
![image](https://user-images.githubusercontent.com/94740533/223123422-35b466a6-6e21-4a1f-8fa7-d41002e63e3d.png)

**Comment by goldsergeant** [comment]
지금 제출이 안되고 빨간색 체크무늬만 떠요.
![image](https://user-images.githubusercontent.com/94740533/223123133-fb06819a-e091-4c61-9028-7f34eb642428.png)

**Comment by PlzNoErr** [comment]
저도 오늘 아침부터 똑같은 문제가 발생했습니다.... 너무 잘쓰고 있고 개발자님께 감사하고 있습니다. 꼭 좀 해결해주세요 ㅠㅜㅜ 허브 없으면 피붕이 죽어유 ㅜ

**Comment by in-jun** [comment]
저도요ㅜㅜ

**Comment by watanka** [comment]
저두요ㅠ

**Comment by khnemu11** [comment]
현재 CORS문제 발생하여 생긴 버그입니다.

만약 당장 급하신거면 Allow CORS: Access-Control-Allow-origin 크롬 확장 프로그램을 이용해서 Access-Control-Allow-origin 설정을 *로 바꾸시거나 Access-Control-Allow-method에 patch를 추가하면 정상작동하니 참고하시길 바랍니다.
