### ISSUE TITLE
현재 백준 CORS 에러 임시 방편( 아침에 해보니까 안되는 경우도 있네요.. )

### ISSUE THREAD

**Issue by Choi-HyunHo** [BaekjoonHub/BaekjoonHub#170]
현재 백준 CORS 에러 임시 방편

브라우저 : 크롬

크롬 확장 프로그램 
1. https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf 다운
2. cors off 한 상태로 아래 체크
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/87301268/223166197-5769ebfa-6320-40a2-8341-775f9bc3e5f6.png">

해결 이미지
<img width="953" alt="image" src="https://user-images.githubusercontent.com/87301268/223166381-61e003ae-b061-4141-a972-cd93a2aaaced.png">

**Comment by kkeolmusae** [comment]
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/35340846/223173317-d126d474-6eec-46f8-9445-bf99f4427d84.png">
<img width="869" alt="image" src="https://user-images.githubusercontent.com/35340846/223173362-56cc49aa-c325-458d-9365-4773c5cfa2ae.png">

FYI, click Reload active tab after cors off 

<img width="876" alt="image" src="https://user-images.githubusercontent.com/35340846/223174567-20086bf3-f91a-48b5-a358-a41707d56ced.png">

**Comment by wonholim** [comment]
다해도 해결이 되지 않는 분들은  1번 칸에 PATCH를 추가하고, 2번을 체크해주세요

**Comment by Sallyrideauto** [comment]
시도 해 봤는데도 해결이 안 됩니다....

**Comment by ddozza54** [comment]
여전히 안됩니다아

**Comment by HosikKim** [comment]
https://chrome.google.com/webstore/detail/moesif-origin-cors-change/digfbfaphojjndkpccljibejjbppifbc/related?hl=ko
설치후 on 시켜주니 저는 바로 업로드 되긴했습니다..

**Comment by Seona056** [comment]
설치 후 on 시키니 되네요! 문제 풀었지만 업로드 되지 않은 문제들의 **[내 제출]**에 들어가기만 해도 자동 업로드 되었습니다! 감사합니다👍

**Comment by c2lv** [comment]
> https://chrome.google.com/webstore/detail/moesif-origin-cors-change/digfbfaphojjndkpccljibejjbppifbc/related?hl=ko 설치후 on 시켜주니 저는 바로 업로드 되긴했습니다..

덕분에 해결했습니다! 감사합니다~
