### ISSUE TITLE
CORS Issue로 인한 업로드 오류 관련 공지

### ISSUE THREAD

**Issue by flaxinger** [BaekjoonHub/BaekjoonHub#172]
안녕하세요?

백준허브 운영자 flaxinger입니다.

CORS 이슈 관련 공지를 어디에 할지 몰라 이슈에 올립니다.

</br>

### 👉 언제 해결되나요?

우선 최근 CORS 이슈로 백준 업로드를 못하는 불편을 겪으시는 사용자분들께 양해를 구합니다.

해당 문제를 해결하기 위해 운영자 및 관계자들이 고민하고 있으며, 

다만 운영자 대부분이 직장인이기에 문제 해결에 시간이 다소 소요될 점 이해 부탁드립니다.

예상 ETA는 금주 일요일입니다. 

(❗ 이번 주 일요일에 크롬 마켓에 검토 점수를 할 예정입니다. 배포는 검토 소요 기간에 따라 다를 수 있습니다)

</br>

### 👉 추가 Action Item

더불어 지금까지 제공되었던 `전체 업로드 기능`은 백준측에 트래픽 스파이크를 발생시키는 주요인이기에,

문제 해결 시점에 지원 중단될 것임을 미리 공지드립니다.

</br></br>

해결 방법 제안은 언제든 환영입니다.

감사합니다.

**Comment by wonholim** [comment]
!

**Comment by prayinforrain** [comment]
안녕하세요, 유익한 익스텐션 감사합니다.
해당 이슈가 해결된 것으로 알고 있는데, Nightly 버전에서는 여전히 커밋이 되지 않고 있습니다.
버전 넘버가 다를 수도 있겠지만 스토어에 표시되는 버전이 일반은 1.1.13, Nightly는 1.1.9로 되어 있는데, Nightly에 해당 이슈가 수정되어 있는 것이 맞을까요?
