### ISSUE TITLE
백준허브 연동 에러

### ISSUE THREAD

**Issue by c2lv** [BaekjoonHub/BaekjoonHub#174]
**버그를 설명해주세요**</br>

Solved.ac 연동 후에도 백준허브 연동 에러가 발생합니다.

**재현 방법을 기술해주세요**</br>

OS: Window 10
익스텐션 버전: 1.1.13(3월 12일 업데이트 버전)
플랫폼: 백준
문제: [1834](https://www.acmicpc.net/problem/1834)
업로드 도중 우측 하단에 에러 메시지가 나타나며 업로드 되지 않는 현상이 발생하였습니다. 
설정 페이지에서 Solved.ac 연동 확인하였습니다.  

**스크린샷**</br>

![오류 화면](https://user-images.githubusercontent.com/50288201/224729223-3ae2af93-0208-472e-acfb-95adfad2c014.png)
![연동 화면](https://user-images.githubusercontent.com/50288201/224729235-74ce00e8-516d-44c5-ad62-45f5e1648607.png)
![개발자 콘솔 화면](https://user-images.githubusercontent.com/50288201/224729240-52e9a95e-a254-425b-83ca-5bf2ff1ce923.png)

**추가 **</br>

확장 프로그램 재설치 후 새 창에서 시도하였으나 동일한 에러 발생하였습니다.

**Comment by flaxinger** [comment]
안녕하세요? 제보 감사합니다.

#175 번 공지 확인을 부탁드립니다. 🙇
