### ISSUE TITLE
백준허브연동 에러

### ISSUE THREAD

**Issue by kyunghyunHan** [BaekjoonHub/BaekjoonHub#177]
문제를 풀고 백준허브를 통해 깃허브에 올리는게 안되네요 cors문제인가싶어  Moesif Orgin &&Cors 이것도 on해놓고 해놓아도 이러네요

![스크린샷 2023-03-16 오전 10 31 58](https://user-images.githubusercontent.com/88940298/225486625-410e43a9-cbaf-42cc-9ad8-b5e6b013d9f9.png)

**Comment by flaxinger** [comment]
#175 이 공지 확인 부탁드립니다.
