### ISSUE TITLE
solved.ac 연동 에러

### ISSUE THREAD

**Issue by SuhyunRim118** [BaekjoonHub/BaekjoonHub#178]
**버그를 설명해주세요**</br>
백준 연동 에러 

**재현 방법을 기술해주세요**</br>
solved.ac가 연동이 되어있음에도 제출 창에 들어가면 백준허브 연동 에러가 계속 뜹니다.

**스크린샷**</br>

**추가 **</br>

**Comment by flaxinger** [comment]
#175 공지 확인 부탁드립니다.

**Comment by flaxinger** [comment]
해결되셨다면 이슈 닫겠습니다.
