### ISSUE TITLE
여러 기기에서 백준허브를 사용할 수 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by RyuJiChang** [BaekjoonHub/BaekjoonHub#179]
**해당 기능이 어떤 문제를 개선하나요?**</br>
다른 컴퓨터에 접속해서 문제를 풀더라도 커밋이 자동으로 되는 기능
(현재는 처음 설치한 컴퓨터에서만 올라가고 그 외 컴퓨터에서는 작동되지 않는다.)

**제안하고 싶은 기능을 설명해주세요**</br>
컴퓨터 OS를 변경하고 싶은데 백준허브가 날아갈까봐 쉽게 변동하지 못하고 있습니다.
여러 곳에서 하더라도 커밋을 할 수 있었으면 좋겠습니다.

**직접 PR 여부**</br>
NO

**Comment by getCurrentThread** [comment]
안녕하세요. 해당 백준허브의 경우에는 크롬 익스텐션으로 
기본적인 동작은 자바스크립트를 페이지에 인젝션 하는 형태로 동작합니다.

크롬 브라우저에 익스텐션이 설치 가능한 환경에서는 모두 사용 가능합니다.
답변이 충분히 되셨으면 코멘트 닫도록 하겠습니다.
(기본 크롬 모바일인 경우에는 현재 익스텐션 설치를 지원하지 않고 있습니다)
