### ISSUE TITLE
백준 14935 문제 업로드가 안 됩니다.

### ISSUE THREAD

**Issue by Sallyrideauto** [BaekjoonHub/BaekjoonHub#181]
잘 되다가 갑자기 또 업로드가 안 되기 시작하네요;;
macOS Chrome 사용 중입니다.
<img width="321" alt="스크린샷 2023-03-31 21 09 48" src="https://user-images.githubusercontent.com/61389628/229116713-ca82139f-b6e3-45ad-9d22-a6812b5b19f8.png">

**Comment by getCurrentThread** [comment]
크롬 개발도구(F12)를 키신 후에 에러 내역 확인해주시기 바랍니다.
만료된 Auth 토큰에 대한 문제일 수 있으므로 
백준허브를 삭제 후에 재설치 해보시길 권장드립니다.
