### ISSUE TITLE
백준 solved.ac 연동 오류

### ISSUE THREAD

**Issue by euni030** [BaekjoonHub/BaekjoonHub#182]
**버그를 설명해주세요**</br>

백준에서 문제를 풀고 제출했는데
solved.ac을 연동을 하라는 빨간창이 나와서 연동을 했는데도 오류가 뜹니다.

**재현 방법을 기술해주세요**</br>

**스크린샷**</br>

![Uploading image.png…]()

**추가 **</br>

어떻게 해결하면 될까요?ㅠㅠ

**Comment by getCurrentThread** [comment]
크롬 개발도구(F12)를 키신 후에 에러 내역 확인해주시기 바랍니다.
만료된 Auth 토큰에 대한 문제일 수 있으므로
백준허브를 삭제 후에 재설치 해보시길 권장드립니다.
