### ISSUE TITLE
프로그래머스 깃허브 업로드 안됨(CORS)

### ISSUE THREAD

**Issue by PhilPark-geosr** [BaekjoonHub/BaekjoonHub#185]
**버그를 설명해주세요**</br>

프로그래머스에서 문제를 제출했을때 빨간색 체크가 뜨면서 업로드가 안됨
검사창에서 확인해보니, CORS가 막혀있음

**재현 방법을 기술해주세요**</br>

조치했던 사항 : 1) moesif 설치 및 수행 -> 안됨
2) Access-Controll-Allow-Origin extension 설치 및 수행 -> 안됨

**스크린샷**</br>

![image](https://user-images.githubusercontent.com/63230370/231915605-5c82e0bb-dfbe-47aa-a203-0d11f1f4b0ff.png)
![image](https://user-images.githubusercontent.com/63230370/231915695-68c86355-c285-4c8c-8954-e69e7052740e.png)

**추가 **</br>

**Comment by getCurrentThread** [comment]
안녕하세요. 프로그래머스 사이트에서는 순수 페이지 파싱으로 진행되기에 
깃허브 외에는 외부 사이트와의 통신이 발생하지 않습니다.
적어주신 내용의 CORS 발생은 사이트 내 또는 타 익스텐션에서 발생된 것으로 추정됩니다.
익스텐션 재설치와 Auth과정을 다시 진행해보시기 바랍니다.
