### ISSUE TITLE
⚠️ 2023-04-16 패치로 인한 이슈는 여기에 남겨주세요! ⚠️

### ISSUE THREAD

**Issue by getCurrentThread** [BaekjoonHub/BaekjoonHub#188]
안녕하세요. 백준허브 익스텐션 메인컨트리뷰터 @getCurrentThread 입니다.
최근 크롬 업데이트로 인한 CORS 정책 업데이트로 인하여 익스텐션 내에 여러가지 패치를 진행하였습니다.

그와 관련하여 기존에 안정성에 대해 문제 시 되어왔던 
Auth token을 가져오는 App 구성을 조금 달리 하였습니다.

현재 당장에는 사용에는 문제가 없으시겠지만, 기존 토큰이 만료되는 등 
동작 불가 이슈가 추가적으로 발생할 예정입니다.

관련 이슈가 발생한다면 **반드시 백준허브를 재설치 해보신 후 동작 문제를 다시 확인**하시고
그 후에 해당 이슈 하단에 코멘트를 남겨주시기 바랍니다.

이후에 안정성과 관련된 이슈가 별도로 생성된 경우에는 답변이 어려울 수 있다는 점 양해 부탁드립니다.

**Comment by woojunro** [comment]
백준 5430번 제출 시 아래 두 에러가 발생하면서 커밋이 되지 않습니다.

```
error ocurred:  TypeError: Cannot read properties of undefined (reading 'tags')
    at parsing.js:247:41
    at async findData (parsing.js:29:26)
    at async baekjoon.js:36:27
```
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at makeDetailMessageAndReadme (parsing.js:48:33)
    at findData (parsing.js:30:20)
    at async baekjoon.js:36:27
```

혹시나 해서 재설치를 해보았는데 같은 에러로 깃허브에 커밋되지 않습니다. 혹시 제가 설정에서 놓친 것이 있는지, 해결방법이 있는지 알려주시면 감사하겠습니다.

**Comment by xoxojw** [comment]
<img width="1470" alt="스크린샷 2023-06-02 오후 2 36 41" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/124491335/486acc65-cda8-4791-b438-7c7732f0b49a">

안녕하세요! 백준허브 익스텐션을 얼마 전에 알게 되어 잘 쓰고 있습니다.

윈도우 데스크탑에서는 문제를 풀고 나면 깃허브에 커밋 생성이 정상적으로 작동하는데요,
문제는 맥북으로 똑같이 하면 하면 빨간 체크가 뜨면서 커밋이 생성되지 않는 이슈가 있습니다.
구글링 해봤는데 저와 같은 이슈를 겪으신 글을 찾을 수 없어 여기에 댓글 남깁니다!
(이 스레드에 글을 남기는게 맞는지도 모르겠어요 ㅠㅠ)

도움이 될까 하여 개발자 도구 에러 로그 스크린샷도 함께 첨부합니다.

감사합니다!

**Comment by getCurrentThread** [comment]
@xoxojw 여러대의 기기에서 개별적으로 사용 가능하십니다.
레포지토리 연결 또는 github API를 동작시키기 위한 토큰 정보의 갱신이 제대로 수행되지 않은 것으로 보여집니다.
번거롭겠지만 익스텐션을 재설치 하시고, 레포지토리 연결이 되셨는지 확인. 그 후에 백준 1000번째 문제를 풀어보셔서 제대로 커밋이 올라가는지 확인해보시기 바랍니다.

**Comment by getCurrentThread** [comment]
@woojunro 백준 내에 추가된 태그에 경우에는 인식을 못하는 버그가 있는 것으로 여겨집니다.
해당 문제는 fix가 필요할 것으로 여겨지는데, 현재 개인사정으로 인하여 작업이 어려운 상태입니다.
이 부분에 대해서 직접 수정해보실 의향이 있으시면 PR 후에 코멘트 부탁드리겠습니다 🙏

**Comment by xoxojw** [comment]
> @xoxojw 여러대의 기기에서 개별적으로 사용 가능하십니다. 레포지토리 연결 또는 github API를 동작시키기 위한 토큰 정보의 갱신이 제대로 수행되지 않은 것으로 보여집니다. 번거롭겠지만 익스텐션을 재설치 하시고, 레포지토리 연결이 되셨는지 확인. 그 후에 백준 1000번째 문제를 풀어보셔서 제대로 커밋이 올라가는지 확인해보시기 바랍니다.

방금 데스크탑, 랩탑으로 테스트해보니 잘 됩니다! 뭔가 중간에 꼬였었나봐요 ㅠㅠ 익스텐션 정말 잘 쓰고 있습니다 감사합니다~!
