### ISSUE TITLE
대회 진행중일 때 소스코드를 제출한 문제에 대해 대회를 끝내고 다시 올릴 때 업로드가 안 되는 버그

### ISSUE THREAD

**Issue by dj-lumiere** [BaekjoonHub/BaekjoonHub#195]
**버그를 설명해주세요**</br>

버그 요약 : 스크린샷과 같이 대회 전에 제출된 소스코드가 번호명이 덮어씌워지지 않는 경우 발생하는 현상임.
대회가 끝났음에도 불구하고 "정책상 대회 문제는 업로드 되지 않습니다. 대회 문제가 아니라고 판단된다면 이슈로 남겨주시길 바랍니다."라는 에러를 띄움.
**재현 방법을 기술해주세요**</br>

현재 사용중인 환경
OS : Windows 11 Education 22H2 22624.1755
경험	Windows Feature Experience Pack 1000.22642.1000.0
Chrome version : 113.0.5672.127 (공식 빌드) (64비트) (cohort: Stable) 
익스텐션 버전 : 1.1.15
플랫폼 : 백준
문제 : 28097, 27918에서 발견
**스크린샷**</br>

<img width="1280" alt="image" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/29950471/aabbecf2-0e26-4a52-8441-ce096562e08e">
**추가 **</br>

**Comment by getCurrentThread** [comment]
안녕하세요. 부득이하게 현업이 바빠 확인을 못드렸네요. 늦게나마 회신 드립니다.
해당 사항은 실행시간이 더 짧아 더 성능이 좋은 것으로 판단되는 제출번호 61050446번이 
최종 업로드가 되어 생기는 문제로 보여집니다.

여기에 대한 예외처리가 필요할 것으로 보여지는데, 
현재 개인사정으로 인하여 이에 대한 유지보수를 진행하기가 어려울 것 같습니다.

직접적으로 PR을 하셔서 수정이 필요하시다면 코멘트 남겨주시기 바랍니다. 🙏
