### ISSUE TITLE
원하는 풀이를 푸시하는 기능을 추가해 주세요

### ISSUE THREAD

**Issue by line1029** [BaekjoonHub/BaekjoonHub#196]
**해당 기능이 어떤 문제를 개선하나요?**</br>

현재 최고 성능의 풀이가 제출되도록 되어있는데, 원하는 풀이가 최고 성능의 풀이보다 성능이 낮은 경우 풀이가 갱신이 되지 않습니다.

**제안하고 싶은 기능을 설명해주세요**</br>

원하는 풀이를 직접 레포지토리에 푸시할 수 있는 기능을 추가해 주시면 감사하겠습니다. 이 경우 원하는 풀이를 푸시한 후 최고 성능 코드를 다시 방문하면 재갱신 될 수도 있을 것 같은데, 로직 최상단에 매뉴얼 푸시인지의 여부를 추가하여 이미 직접 푸시한 풀이는 갱신이 되지 않도록 하면 좋을 것 같습니다.

**직접 PR 여부**</br>

'NO'

**Comment by getCurrentThread** [comment]
안녕하세요. 해당 기능은 이전에 개발 검토 단계에서 
기존의 자동 업로드 기능과의 충돌 상황에 대한 예외처리와 함께
익스텐션을 사용하는 사용자의 추가적인 피로에 관여할 여지가 
클 것이라는 의견으로 기능 추가에서 제외되었습니다.

별도로 옵션의 형태로 추가하여 운영코자 하신다면 
fork를 수행하셔서 코드를 변경 후에 개별적으로 사용하셔도 무방합니다.
