### ISSUE TITLE
백준 문제들을 단계별 말고도 알고리즘 별로도 분류할 수 있게 해주세요!

### ISSUE THREAD

**Issue by kimchiramenclub** [BaekjoonHub/BaekjoonHub#197]
**해당 기능이 어떤 문제를 개선하나요?**</br>

문제들을 다시 볼 때, 원하는 알고리즘 별로 볼 수 있게 됩니다.  

**제안하고 싶은 기능을 설명해주세요**</br>

BRONZE, SILVER 이렇게 단계별로 구분하는 것 외에도,</br>
DP, Brute Force 이런 식으로 알고리즘 별로도 폴더가 구분돼서 좀 더 쉽게 복습할 수 있음 좋겠습니다!</br>

**직접 PR 여부**</br>
NO

**Comment by getCurrentThread** [comment]
#163 과 중복되는 내용으로 보여집니다.

 이는 템플릿 처리가 불가결해 보이는데,크롬 익스텐션에서는 자바스크립트를 eval 함수라던가 별도의 함수 문자열을 실행하는 방법으로 동작하는 그러한 XSS 형태의 유저스크립트가 사용될 수 있는 여지의 익스텐션은 업로드하지 못하도록 운영하고 있는 실정입니다. 이 부분에 대해서는 여러 면모로 검토가 필요할 것 같습니다 😅 .
