### ISSUE TITLE
chrome 웹 스토어 설치 오류

### ISSUE THREAD

**Issue by m4nd4r1n** [BaekjoonHub/BaekjoonHub#204]
**버그를 설명해주세요**</br>

chrome 웹 스토어에서 백준 허브 추가 시 `패키지가 잘못되었습니다. 세부정보: 'Could not load icon 'assets/thumbnail.png' specified in 'action'.'.` 오류 발생으로 인한 설치 불가

**재현 방법을 기술해주세요**</br>

OS: macOS Sonoma 14.0
Browser: Chrome 117.0.5938.88(공식 빌드) (arm64)
익스텐션 버전: 1.1.16

**스크린샷**</br>

<img width="538" alt="스크린샷 2023-09-21 18 04 38" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/96206089/a087bd42-9221-4567-8e0d-d40882fe2e7b">

**Comment by WinterFlw** [comment]
동일한 오류 발생
OS 버전 : Window 10 (개인적 사유로 버전 확인 불가)
Chrome 버전 : 107.0.5304.122(공식 빌드) (64비트)
스크린샷
![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/96910692/39afabe0-3b0f-4a41-abea-d9b1b4fad085)

**Comment by getCurrentThread** [comment]
deploy 시에 아이콘 리소스가 누락되는 오류가 있었습니다. 현재 오류 수정하여 스토어 측에 재검토 넣어두었습니다.

**Comment by getCurrentThread** [comment]
@m4nd4r1n @WinterFlw 배포 완료되었습니다.

![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/31976959/5e20611d-ee9c-4e58-916d-dc1c7be091ce)

**Comment by getCurrentThread** [comment]
이슈 닫습니다.
