### ISSUE TITLE
v1.1.19 패치 후 이미 업로드된 코드 재업로드 발생

### ISSUE THREAD

**Issue by zosungwoo** [BaekjoonHub/BaekjoonHub#210]
**버그를 설명해주세요**</br>
v1.1.19 패치 이후 백준 '내 제출' 클릭 시 bojData가 Best Submission으로 잘 계산됩니다.
하지만 이미 업로드가 완료된 Best Submission이 다시 깃허브에 업로드되는 현상이 발생합니다.
```
    /* 현재 제출하려는 소스코드가 기존 업로드한 내용과 같다면 중지 */
    cachedSHA = await getStatsSHAfromPath(`${hook}/${bojData.directory}/${bojData.fileName}`)
    calcSHA = calculateBlobSHA(bojData.code)
    log('cachedSHA', cachedSHA, 'calcSHA', calcSHA)
```
위 코드의 로그를 확인해본 결과, cachedSHA와 calcSHA 값이 달라 재업로드가 진행됩니다.

<br>

**재현 방법을 기술해주세요**</br>
v1.1.19 패치 이후 백준 '내 제출' 클릭 후 '백준허브용 레파지토리' 커밋 내역 확인 바랍니다.

<br>

**스크린샷**</br>
![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/30895117/3d3a54b0-fb97-48ff-8efd-7c9496684f26)

'내 제출'에 들어갈 때마다 업로드가 발생합니다.

**Comment by getCurrentThread** [comment]
@zosungwoo 구현이 안되네요.
해당 문제 해결 될 때까지 게시는 지연합니다.

**Comment by zosungwoo** [comment]
혹시 12845번 문제로 재현되는지 확인해주실 수 있으실까요?

**Comment by zosungwoo** [comment]
![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/30895117/9a725af9-8c47-4385-916c-38551b63753f)
문제 발생하는 '내 제출' 페이 스크린샷도 함께 첨부합니다.

**Comment by zosungwoo** [comment]
한 문제 더 발견하여 추가로 올립니다.

<img width="1156" alt="image" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/30895117/a17121df-9af8-421f-b52e-3e020d29fda7">

<img width="579" alt="image" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/30895117/87cd6bcc-c3bf-4d2e-bf11-5c54ff3b16dc">
