### ISSUE TITLE
백준 특정 문제에서만 커밋이 올라가지 않습니다.

### ISSUE THREAD

**Issue by Sumin-Kim-dev** [BaekjoonHub/BaekjoonHub#213]
**버그를 설명해주세요**</br>

다른 문제는 커밋이 잘 올라가는데, 백준 14935번만 커밋이 올라가지 않고 있습니다.
참고로, 해당 문제는 코드 길이가 비공개로 설정된 문제입니다.
코드 길이가 비공개인 다른 문제에서도 같은 현상이 발생하는지는 확인하지 못했습니다.

**재현 방법을 기술해주세요**</br>

백준 14935번 문제에서 백준 허브를 통해 커밋을 날렸습니다.

**스크린샷**</br>

거의 동일한 시간에 업로드를 시도하였습니다. 14935번만 올라가지 않음을 확인할 수 있습니다.
![캡처](https://github.com/BaekjoonHub/BaekjoonHub/assets/87856793/be87561c-be47-419e-b62e-eb55f538aea7)
![캡처2](https://github.com/BaekjoonHub/BaekjoonHub/assets/87856793/88f673d6-de78-4d7c-9ed3-dd9be4529a5a)

실패하였을 때 개발자도구 콘솔을 캡처하였습니다.
![캡처3](https://github.com/BaekjoonHub/BaekjoonHub/assets/87856793/d5295559-89cd-4035-9f9d-ed6cd27b27c1)

**추가 **</br>

**Comment by getCurrentThread** [comment]
우선 소중한 시간을 사용해 이슈를 주셔서 감사합니다. 
해당 문제의 버그를 재현하고 다시 확인한 후 수정하도록 하겠습니다. 👍

**Comment by getCurrentThread** [comment]
메모리와 시간 데이터를 수정하는 부분이 있는데, 
이 부분에서 데이터가 없으면 타입 에러가 발생하는 부분이었네요. 
추후 수정할 예정입니다.

**Comment by h0pler** [comment]
같은 문제를 겪고 있습니다. 아직까지 수정되지 않았습니다.
추후 수정 계획이 없으신가요?

**Comment by SeungAhSon** [comment]
9987번 문제도 올라가지 않습니다. 같은 오류인 것 같아요.

**Comment by tjkpolisher** [comment]
1402번 문제도 올라가지 않는 것 같습니다. 오늘 다른 문제는 정상적으로 커밋되는 것 확인했습니다.

**Comment by Jeonous** [comment]
12261번도 업로드 되지 않는데 원인을 몰라서 이 이슈에 남깁니다.

빨간색 체크표시가 뜹니다.

https://www.acmicpc.net/problem/12261

**Comment by jiho7407** [comment]
https://www.acmicpc.net/problem/16461

해당 문제에서도 같은 오류가 일어나는것으로 보입니다! 무슨 오류인지 신기하네요

**Comment by getCurrentThread** [comment]
@all #262 를 통하여 오류 해소 완료하였습니다.

**Comment by Jeonous** [comment]
안녕하세요? 에러 수정에 감사드립니다.

이에 따라 이전에 제가 말씀드렸던 5개의 문제들에 대해 다시 커밋을 시도했는데, 그 중 3문제는 여전히 커밋실패가 뜹니다.

해당 문제 목록은 다음과 같습니다.
https://www.acmicpc.net/problem/16850 
https://www.acmicpc.net/problem/4322 
https://www.acmicpc.net/problem/13845
