### ISSUE TITLE
2023-10-20부터 레포지토리에 저장이 되지 않습니다.

### ISSUE THREAD

**Issue by highlaw00** [BaekjoonHub/BaekjoonHub#214]
**버그를 설명해주세요**</br>

![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/65754646/d5431d27-ceb8-48ac-89fd-12a003cb1bef)
![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/65754646/67cb5e44-12d6-4103-840a-e96ce3e9c82b)
20일부터 레포지토리에 푸쉬가 되지 않습니다. (각각 20일, 21일에 해결한 문제이나 아직 푸쉬가 되지 않음)

**재현 방법을 기술해주세요**</br>
생략.

**스크린샷**</br>

상위 첨부.

**추가 **</br>

**Comment by getCurrentThread** [comment]
익스텐션을 재설치 한 뒤에 재확인 부탁드립니다.
