### ISSUE TITLE
문제번호 순서대로 백준 푼 문제가 정렬되었으면 좋겠습니다.

### ISSUE THREAD

**Issue by SehyunPark** [BaekjoonHub/BaekjoonHub#217]
**해당 기능이 어떤 문제를 개선하나요?**</br>
 문제번호 id 오름차순으로 푼 문제가 정렬되면 더 보기에 깔끔할 것 같습니다. 예를 들어 제가 10026번과 1038번을 풀었다면 10026 문제가 상위, 그리고 1038이 그 아래에 나오는데 번호 오름차순으로 1000번부터 차례대로 나열되면 좋겠습니다.

**제안하고 싶은 기능을 설명해주세요**</br>
 번호 오름차순 정렬. (ex: 1033, 10001, 10212, 11000 번 문제를 풀었다면 문제번호 오름차순으로 1033이 상위에 10001 10212 10000 순으로)

**직접 PR 여부**</br>
 NO

**Comment by getCurrentThread** [comment]
안녕하세요. 현재 커밋할 디렉토리를 커스텀하는 기능이 존재치 않아서 해당 기능을 제공하기에 어려움이 많습니다.

**Comment by getCurrentThread** [comment]
해당 기능을 직접 PR로 넣어주시는 경우 검토해보고 적용하도록 하겠습니다.
