### ISSUE TITLE
레포지토리 설정시 하위 폴더까지

### ISSUE THREAD

**Issue by peteryu24** [BaekjoonHub/BaekjoonHub#218]
처음 레포지토리를 설정할 때 레포지토리 내부 하위 폴더에 커밋하도록 설정하고 싶은데,
하위 폴더까지 디렉토리를 설정해서 세팅하려고 하면 잘못된 url이라고 뱉어냅니다.
하위 폴더에 커밋되도록 설정하려면 어떻게 url을 세팅해야 하나요?
![백준허브 ](https://github.com/BaekjoonHub/BaekjoonHub/assets/67302252/10900ee8-d9a0-4a3a-b070-8555b2f314e6)

직접 PR 여부
NO

@getCurrentThread

**Comment by getCurrentThread** [comment]
하위 폴더에 커밋할 수 있도록 하는 기능은 현재 백준허브에 없는 기능입니다.

**Comment by peteryu24** [comment]
답변 감사합니다
