### ISSUE TITLE
깃허브 커밋만 하거나 커밋&푸시를 하는 기능이 생겼으면 합니다

### ISSUE THREAD

**Issue by c1vera** [BaekjoonHub/BaekjoonHub#219]
**해당 기능이 어떤 문제를 개선하나요?**</br>

저는 친구들과 공부를 위해 만든 디스코드 방이 있는데, 여기서 깃허브 웹훅을 이용해서 커밋 로그를 남기고 있습니다. 백준 문제들을 풀 때 풀면서 매번 커밋&푸시가 되니 많은 문제를 풀면 커밋 로그를 제가 전부 도배하는 일이 생기곤 합니다. 이러한 일을 방지하면 좋을 것 같습니다.

**제안하고 싶은 기능을 설명해주세요**</br>

백준, 프로그래머스 문제를 풀면 자동으로 커밋되고, 확장 프로그램 메뉴 창에서 푸시 해주는 버튼이 생겼으면 합니다.
이전 유저들을 위해 커밋&푸시 한번에 하기/푸시를 따로 하기 이런식으로 옵션이 생기면 편할 거 같습니다!

**직접 PR 여부**</br>

NO

**Comment by getCurrentThread** [comment]
안녕하세요. 해당 기능을 현재 구현하기에는 현업으로 인하여 어려움이 많은 상황입니다.
만해당 기능을 직접 개발하셔서 PR 해주신다면 검토 후에 반영토록 하겠습니다.
