### ISSUE TITLE
첫 제출 이후 수정한 코드를 커밋,푸쉬 하고싶습니다.

### ISSUE THREAD

**Issue by HongKyoungIn** [BaekjoonHub/BaekjoonHub#220]
첫 문제 풀이 제출 이후 수정한 코드가 깃허브에 올라가지 않아요.
처음으로 푼 이후 추가적으로 찾은 내용이나 혹은 더 좋은 코드를 짜서 새로운 코드로 수정해서 제출 완료 했을 때 변경된 코드를 올리고 싶은데 올라가지 않습니다.

**Comment by getCurrentThread** [comment]
안녕하세요. 백준허브는 현재 실행시간이 더 짧은 결과를 기준으로 업로드가 진행됩니다. 
그 외의 기능적으로 해당 내용을 추가하고 싶으시다면 
해당 기능을 만드셔서 직접 PR를 해주시면 검토 후 반영토록 하겠습니다 :)

**Comment by rladntlr** [comment]
안녕하세요 같은 문제를 여러번 풀어도 실행시간이 가장 짧은 결과를 기준으로 올라가는 것이라고 생각 하면 되는걸까요? 제가 계속 문제를 풀어도 제출 일자가 과거 시간으로 나와서 문의 드립니다.

**Comment by journeythrunrun** [comment]
@HongKyoungIn 
- 참고할 사항
제가 앞으로 더 많이 쓸 일이 없을 것 같아서 기능 구현된 코드 읽거나 개선하기한 건 아니고 시행 착오로 알게 된 우회해서 해결하는 방법입니다.

제가 개인적으로 볼 용으로 주석 필기했던 거 일부 잘라서 복붙한 거라 이해가 덜 가실 수도 있습니다.

- 제 케이스에서 해결 가능했던 방법, 맥락 쫌 더 담긴 원문 링크

백준의 내제출에서 다음 페이지로 넘어간 그 빠른 코드는 안읽혀서 이전 최신 본이 다음 페이지로 넘어가도록 계속 제출하면 됨.
#    > 반복 돌릴 때_오래걸리게 해두기(타이밍에 의해서 확률 적은 최단 기록으로 갱신해버리면 귀찮아지기 때문에.. 타이밍에 의한 이전 최단은 반복하면 뜨겠지)
'''
for i in range(100000):
    hi=1
'''

https://github.com/journeythrunrun/01-coding-test/blob/main/%EB%B0%B1%EC%A4%80/Gold/9205.%E2%80%85%EB%A7%A5%EC%A3%BC%E2%80%85%EB%A7%88%EC%8B%9C%EB%A9%B4%EC%84%9C%E2%80%85%EA%B1%B8%EC%96%B4%EA%B0%80%EA%B8%B0/%EB%A7%A5%EC%A3%BC%E2%80%85%EB%A7%88%EC%8B%9C%EB%A9%B4%EC%84%9C%E2%80%85%EA%B1%B8%EC%96%B4%EA%B0%80%EA%B8%B0.py
