### ISSUE TITLE
백준허브 레포 소개글 수정 요청

### ISSUE THREAD

**Issue by psrom** [BaekjoonHub/BaekjoonHub#222]
**해당 기능이 어떤 문제를 개선하나요?**</br>

영어 문법을 개선할 수 있습니다.

**제안하고 싶은 기능을 설명해주세요**</br>

**기존**
This is **a** auto push repository for Baekjoon Online Judge created with [BaekjoonHub](https://github.com/BaekjoonHub/BaekjoonHub).

**제안**
This is **an** auto push repository for Baekjoon Online Judge created with [BaekjoonHub](https://github.com/BaekjoonHub/BaekjoonHub).

**직접 PR 여부**</br>

NO

**Comment by getCurrentThread** [comment]
#221 에서 해결되었습니다 :)
