### ISSUE TITLE
문제가 제대로 불러와 지지 않았어요

### ISSUE THREAD

**Issue by yelwhiltelow** [BaekjoonHub/BaekjoonHub#223]
**버그를 설명해주세요**</br>
백준  21757 - 나누기 문제를 65점으로 풀고 난 후 허브에 들어가 봤는데 문제가 약간 이상하게 복사가 되어있었습니다. 아마 수식으로 표현된건 다 이렇게 되는거 같아요.

**재현 방법을 기술해주세요**</br>

**스크린샷**</br>
백준 허브에 나온 내용
<img width="1048" alt="스크린샷 2024-01-08 오후 3 25 47" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/97219029/57cbfd8e-58fd-4fbb-b72c-478ef664dd96">
실제 문제 내용
<img width="1166" alt="스크린샷 2024-01-08 오후 3 26 32" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/97219029/bed74b39-f956-4667-bdd7-74c7cab11e7f">

**추가 **</br>
그런데 부분점수도 올라가는게 원래 기능인가요?

**Comment by getCurrentThread** [comment]
24시간 후에 닫도록 하겠습니다.
