### ISSUE TITLE
확장프로그램 미작동 이슈 (해결완료)

### ISSUE THREAD

**Issue by ellisajung** [BaekjoonHub/BaekjoonHub#226]
**버그를 설명해주세요**</br>

백준, 프로그래머스 둘다 문제 푼 후 로딩표시나 빨간체크표시 아무것도 뜨지 않습니다.

**재현 방법을 기술해주세요**</br>

맨처음 설치후 푼 첫 백준 문제는 성공적으로 연동이 되었으나,
프로그래머스는 연동이 안돼서 확장 재설치, 재연동, 깃허브앱 재연동, 레포 재설정 등 시도를 해봤는데
지금은 프로그래머스와 백준 둘다 밑에 사진처럼 안됩니다.

**스크린샷**</br>

<img width="1219" alt="스크린샷 2024-01-15 오후 9 21 45" src="https://github.com/Bae
<img width="1262" alt="스크린샷 2024-01-15 오후 9 24 43" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/125180849/b223e720-806e-48a5-8a21-dbcdbbd600ac">
kjoonHub/BaekjoonHub/assets/125180849/7430538f-2cd6-436e-b44b-96a9043ce055">
<img width="1195" alt="스크린샷 2024-01-15 오후 9 26 01" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/125180849/292cab33-f72e-4f6c-93a1-e4303b69c18a">
<img width="931" alt="스크린샷 2024-01-15 오후 9 26 39" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/125180849/862236f9-b73a-443d-b0e5-c0233dbe3461">

**추가 **</br>

**Comment by bbijoum26** [comment]
혹시 해결 되셨나요?

**Comment by hongxeob** [comment]
저도 현재 백준은 잘 저장되는데, 프로그래머스는 체크 표시등이 뜨지 않아 저장이 되지 않네요.

**Comment by oauch** [comment]
어제까지는 잘 됐는데 오늘 갑자기 안되네요

**Comment by serendipity63** [comment]
저도 어제까지는 되었는데 오늘 안되네요...

**Comment by Middledown** [comment]
아직 반영이 안된 것 같습니다.. 프로그래머스에서 똑같이 동작하네요
![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/124867768/f8888c40-d137-465c-a504-f06ea26fdcfa)

**Comment by Jiwonp12** [comment]
저도 오늘 갑자기 안되네여

**Comment by dayul** [comment]
저도 갑자기 안됩니다 ㅜㅜ 3일전까지만 해도 잘 됐었는데요

**Comment by Eeeevee** [comment]
3주 전부터 그런거 같은데 아직 해결 안됐나요? 빠른 처리 부탁드립니다,

**Comment by dkagh012** [comment]
3일 전에 잘 됐는데 지금 안되네요..

**Comment by sy97** [comment]
저도 갑자기 안되는데, 방법없나요..?

**Comment by cofla159** [comment]
문제를 꼼꼼하게 예제까지 읽자!
"나머지 문자열의 **괄호 방향**을 뒤집어서"라고 돼있는데 순서를 뒤집어버렸다!!

**Comment by twodf78** [comment]
백준허브 재설치, 기존 레포 재연결, 새로운 레포 연결, 등 방법으로 시도 해봤는데 해결이 안 됩니다.
다른 방법이 있을까요?

**Comment by Hyerim926** [comment]
제 환경 문제가 아니었군요. 프로그래머스 어제 잘 사용했는데 지금 사용해보니 안됩니다.

**Comment by BreadQuokka** [comment]
프로그래머스 커밋 안되는거 오류인가용..?

**Comment by cookieunnie** [comment]
저도 어제는 잘 됬는데, 오늘 안됩니다 ㅠㅠ 재설치, 레포 재연결 모두 해봐도 안돼요....

**Comment by ted0729** [comment]
어제까진 잘 됬는데 안되네요 ㅠ,.ㅠ

**Comment by BaeDongWoo** [comment]
헐 저만 그런게 아니었군요

**Comment by beginner0107** [comment]
어 저도 안 되네요. 허걱..

**Comment by GaHee99** [comment]
저도.. 둘다 안되네요, 
재설치 레포 재연결 둘다 소용 없습니다. ㅜㅜ

**Comment by howooyeon** [comment]
저도 안됩니다..

**Comment by GaHee99** [comment]
혹시 깃허브 2단계 인증 이후로 안되시나요.?> 안됩니다..

**Comment by Jung-10** [comment]
저도 갑자기 어제부터 안됩니다,, 재설치도 해봤는데 백준은 되는데 프로그래머스는 안되네요,, 지금 프로그래머스가 연동이 안되는게 맞는건가요?ㅜㅜ

**Comment by AHEAD94** [comment]
저도 마찬가지로 어제까진 잘 되었는데, 오늘 깃허브 컨트리뷰션이 안뜨네요ㅠㅠ
가끔 한문제씩 안올라가는 문제가 있어서 다음 문제는 뜨겠지, 또 다음 문제는 뜨겠지 하면서 몇문제를 푼건지ㅋㅋㅋ 오히려.. 좋나?
하지만 잔디 못심은게 아쉽습니다 ㅠ

**Comment by SayisMe** [comment]
같은 이슈입니다. 자동업로드가 안되네요

**Comment by JiungPark** [comment]
저도 어제부터 갑자기 안됩니다.. 이것저것 다 시도 했는데 안되네요 ㅠ

**Comment by getCurrentThread** [comment]
프로그래머스 핫픽스 배포로 문제 해소중입니다. :)

**Comment by AHEAD94** [comment]
빠른 대응 감사드립니다!

**Comment by lejehwan** [comment]
watch

**Comment by BillionDollarSohee** [comment]
저두 이글 못봤으면 제문제인줄알고 계속 헤맸을 것 같네요 감사합니다 ㅠㅠ

**Comment by goyomi** [comment]
어제부터 갑자기 안되서 찾아왔는데 해결중이시군요 ㅠ_ㅠ 화이팅 🔥🔥

**Comment by Jih00nJung** [comment]
항상 잘 쓰고 있습니다 감사합니다! 화이팅^^

**Comment by Ko-udon** [comment]
저만 안되는게 아니였군요
빠르게 대응해주시고 감사합니다!

**Comment by wjdwnsdnjs13** [comment]
ㅠㅠ 갑자기 안돼서 보고 있었는데
2중 보안 걸어서 그거 때문인가 싶어서 한참 헤맸네요 ㅋㅋ
항상 잘 쓰고 있습니다 ㅎㅎ 감사합니다!

**Comment by fabric0de** [comment]
이슈 해결 기원하겠습니다!!
항상 감사합니다~

**Comment by MinnSeoo** [comment]
저도 어제부터 갑자기 안되서, 제 문제인줄 알았는데.. 아니였군요..ㅠ
빠른 해결 기원하겠습니다!! 화이팅!! 🔥

**Comment by KimBeomGi** [comment]
아 저도 왜안되지왜안되지 하다가 들어왔는데, 해결중이시군요 화이팅입니다!
잘쓰고 있습니다. 감사합니다!

**Comment by Seongjoon-Jeong** [comment]
오 다시 됩니다~!

**Comment by Aleph-Kim** [comment]
오오 정상작동합니다!!
![스크린샷 2024-02-07 오전 9 42 31](https://github.com/BaekjoonHub/BaekjoonHub/assets/93961956/626a7ad4-3136-4dcf-a38f-079a6f1af20f)

**Comment by GaHee99** [comment]
오..저는 안되는 것 같은데 되시는 분들 다시 install하신건가요?

**Comment by Jung-10** [comment]
저도 안되는데 다른 분들은 그냥 된건가요??

**Comment by Eeeevee** [comment]
재설치 하니 정상적으로 작동 되네요! 해결 감사드립니다

**Comment by oweaj** [comment]
삭제 후 재설치 하니 정상 작동 되네요 해결 감사합니다~!

**Comment by getCurrentThread** [comment]
![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/31976959/6822b8d2-90cc-43c0-9ad7-9abae0033f9c)
5월 6일 오후 5시 이후로 검토 후 익스텐션 배포 완료되었습니다. 
아직 적용되지 않으신 분들은 익스텐션 삭제 후 다시 설치해보시길 바랍니다.

**Comment by getCurrentThread** [comment]
24시간 이후 해당 이슈 닫도록 하겠습니다.

**Comment by minjo0n61** [comment]
저도 안됩니다 ㅠㅠ
확인 부탁드립니다..!

**Comment by SeongHuiJung** [comment]
저도 오늘 낮까지만 해도 잘 됐었는데 방금 시도해보니까 안되는 것 같네요. ㅠㅠ
삭제 후 재설치 후 레포지토리 재연결 했으나 체크표시가 아예 안뜹니다...

**Comment by dev-Seonghwan** [comment]
저는 아직도 안되네요 ㅠㅠ

**Comment by serendipity63** [comment]
어제까지 잘 되다가 갑자기 안됩니다

**Comment by kangyeongmin** [comment]
저도 어제까지 잘되다가 안됩니다..
<img width="312" alt="스크린샷 2024-02-21 오전 10 37 37" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/62367797/c7e2e22b-84ce-41a8-bbf4-38cd17d53b80">
<img width="437" alt="스크린샷 2024-02-21 오전 10 37 53" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/62367797/f4cb1523-6f58-435f-b6bc-1cdb78ca2172">

**Comment by mint3382** [comment]
저도 체크표시도 안 뜨고 안됩니다..
삭제 후 재설치 했는데도 안됩니다.
![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/124889931/6059dfcd-d6dc-4b1c-9088-99cf4fd48b29)

**Comment by serendipity63** [comment]
저도 동일한 이슈입니다..

**Comment by inyoungfriend** [comment]
삭제후 재설치했는데 안됩니다~

**Comment by naeun-shin** [comment]
동일한 이슈 발생중인데, 해결 언제쯤 가능하실까요~~~??

**Comment by hyunsookim0813** [comment]
저도 동일한 이슈가 발생해서 연동이 안되네요..

**Comment by microsaurs** [comment]
저도 동일한 이슈로 안됩니다 ㅜㅜ

**Comment by jeongho218** [comment]
프로그래머스에서 푼 문제가 깃허브에 커밋이 보내지지 않는 상황입니다.
개발자도구에서 첨부 사진과 같이 에러 메세지가 나오고 있으니 확인 부탁드립니다.
![캡처](https://github.com/BaekjoonHub/BaekjoonHub/assets/82637024/6228f204-d2fb-45f2-93af-bbfe29868360)

**Comment by ted0729** [comment]
어제까지 잘되다가 안되네용 ㅇ_ㅠ

**Comment by jaeuklim** [comment]
왜 그럴까요 ㅠ

**Comment by minjo0n61** [comment]
지금 잘됩니다!

**Comment by www-author** [comment]
저도 이제 잘 됩니다!

**Comment by silverzoo** [comment]
<img width="1504" alt="Screenshot 2024-03-20 at 11 32 24 PM" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/27897137/116c6c12-3706-4fc0-97f6-5c47bc5b0566">
프로그래머스와 연동이 안됩니다 ㅠㅠ.

**Comment by maxkim77** [comment]
저도 동일 이슈로 8.24. 자로 안됩니다. 이전까지 잘됫는데 url이 바뀐건지..

**Comment by MinSang22Kim** [comment]
레포 이름 바꾸신 분들 다시 연결하시면 잘 동작합니다!

**Comment by jngs-park** [comment]
![Screenshot 2024-10-18 at 00 05 57](https://github.com/user-attachments/assets/a2eb74ee-1c6a-4b1e-a8b8-8ae91ccff92c)
현재 저는 파란체크는 뜨나 기존에 연결되어 있던 레포에 커밋이 안됩니다. 여러번하다보면 간헐적으로 한번 되기도 하며
백준허브 재설치, 레포 재연결해도 안됩니다.

그런데 백준에서 새로운 레포 생성해서 연동하면 그 레포에는 커밋이 되고요. 그 상태에서 다시 기존 레포로 옮기면 다시 안되고 다시 새로 생성해서 연동했던 레포로 돌아가면 또 안됩니다. 현재 무조건 새로 레포 생성해서 연동하게끔만 해야 커밋이 되는데 기존에 사용하던 레포에 함께 커밋하고 싶어서 이렇게 글 남깁니다.
