### ISSUE TITLE
파이어폭스 지원 계획은 없나요?

### ISSUE THREAD

**Issue by ecruosnepo** [BaekjoonHub/BaekjoonHub#229]
**해당 기능이 어떤 문제를 개선하나요?**</br>

파이어폭스 지원</br>
**제안하고 싶은 기능을 설명해주세요**</br>

파이어폭스에서도 백준허브를 사용하고싶습니다. 제발요..</br>
**직접 PR 여부**</br>

NO

**Comment by getCurrentThread** [comment]
추가적인 여력이 없어 해당 지원 계획은 현재까지 없습니다. 
의견 주셔서 감사합니다. :)

**Comment by getCurrentThread** [comment]
해당 이슈 닫습니다. 감사합니다.
