### ISSUE TITLE
프로그래머스 백준 충돌

### ISSUE THREAD

**Issue by cokkiboy** [BaekjoonHub/BaekjoonHub#233]
**버그를 설명해주세요**</br>
프로그래머스에 문제풀다가 백준도해보고싶어서 이용했습니다. 근데  백준에 커밋이되고 프로그래머스에 커밋이안됩니다. 무슨문제일까요?

**재현 방법을 기술해주세요**</br>

**스크린샷**</br>

**추가 **</br>

**Comment by cokkiboy** [comment]
The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field. 이런오류가 뜨네요 프로그래머스 문제풀고나서

**Comment by getCurrentThread** [comment]
#230 에 hotfix에 의해 해소중입니다. 익스텐션 검토 완료까지 기다려주세요.
