### ISSUE TITLE
문제 업로드 시 기존 폴더와 다른 폴더명으로 업로드가 되고 있습니다.

### ISSUE THREAD

**Issue by 98SKC** [BaekjoonHub/BaekjoonHub#239]
**버그를 설명해주세요**</br>

문제 업로드 시 기존 폴더와 다른 폴더에 업로드가 되고 있습니다.
Silver의 경우 Silver I ,Silver II 와 같이 난이도를 의미하는 숫자가 추가되어 폴더가 새로 잡히고 있습니다.
따로 설정이나 컨벤션을 건들지는 않았습니다. 2월14일에 이러한 현상을 발견하여 해결방안을 열심히 찾아보았으나 해결법을 모르겠습니다...

**재현 방법을 기술해주세요**</br>

**스크린샷**</br>

![백준허브](https://github.com/BaekjoonHub/BaekjoonHub/assets/127596280/7f11d34f-6a99-4fc9-adb7-70d3059270d2)

**추가 **</br>

**Comment by thwang26** [comment]
저도 동일한 이슈 발견하였습니다. 기존에 티어로만 분류되었는데 세부 난이도가 추가되어 업로드가 됩니다.

**Comment by JackCme** [comment]
+1 동일한 이슈

**Comment by smpark00** [comment]
동일한 증상 나타납니다

**Comment by getCurrentThread** [comment]
#237 PR로 인한 오류 였습니다. #241 로 해결되었습니다. 익스텐션 업데이트 검토 중입니다.

**Comment by getCurrentThread** [comment]
배포 완료 되었습니다. 

백준허브 익스텐션을 새로 설치하시거나, 
기다리시면 자동으로 업데이트가 진행됩니다.

해당 이슈 24시간 후에 닫도록 하겠습니다!
