### ISSUE TITLE
제출 일자가 시스템 시간과 다르게 기록됩니다.

### ISSUE THREAD

**Issue by yeominstall** [BaekjoonHub/BaekjoonHub#240]
**버그를 설명해주세요**</br>
제출 일자에 기록된 시간이 실제 날짜와 다릅니다. 시간은 일치..하진 않지만 큰 차이 없습니다.

**재현 방법을 기술해주세요**</br>
두 번 시도해서 두 번 모두 잘못된 날짜가 기록되었습니다. 제출 과정 상의 특이 사항은 없습니다.
시스템 시간은 time.windows.com 과 동기화 되고 있습니다.
Win 10 Home, 익스텐션 버전 1.1.24, 프로그래머스, 문제: [완주하지 못한 선수](https://school.programmers.co.kr/learn/courses/30/lessons/42576)
구글 크롬 버전은 업데이트가 진행돼서 확인하지 못했습니다. (업데이트 버전: 121.0.6167.161(공식 빌드) (64비트))

**스크린샷**</br>
![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/8392317/fa9b2572-2434-4230-b8bc-12ccd8639bf1)

**Comment by yeominstall** [comment]
수정된 부분은 BOJ 쪽 함수인 것 같습니다. #240, #243에서 제보 된 환경은 프로그래머스입니다.
이 이슈 제보 이후 BOJ 에서 제출했을 땐 위와 같은 문제가 발생하지 않았습니다. #244 의 수정과 이 이슈는 무관해 보입니다.

**Comment by getCurrentThread** [comment]
@yeominstall 동일 코드가 파편화 되어 있습니다. 프로그래머스 및 SWEA에도 동일 적용 하겠습니다. :)

**Comment by getCurrentThread** [comment]
@yeominstall 어제 오후 9시 44분에 배포 완료되었습니다. 업데이트 확인해보시고 문제 사항이 있으시면 말씀해주시기 바랍니다.

**Comment by getCurrentThread** [comment]
추가사항 없으시면 24시간 후에 이슈 닫도록 하겠습니다.
