### ISSUE TITLE
제출 일자의 일자 기록이 정상적으로 기록되지 않습니다.  

### ISSUE THREAD

**Issue by lhseunge** [BaekjoonHub/BaekjoonHub#243]
**버그를 설명해주세요**</br>

프로그래머스 문제 제출 후 github에 생성된 문제 Readme 파일의 제출 일자가 정상적으로 기록되지 않습니다. 

**재현 방법을 기술해주세요**</br>

맥OS, 1.1.25, 프로그래머스, 입문 문제(0레벨), (120807. 숫자 비교하기, 120805. 몫 구하기)

1. 익스텐션 설치
2. github 연동
3. 새로운 레포지토리 생성으로 백준허브 연동
4. 기존에 풀었던 문제 재 제출
5. 시간 버그 확인 

**스크린샷**</br>

![스크린샷 2024-02-18 오후 11 09 37](https://github.com/BaekjoonHub/BaekjoonHub/assets/107404774/2414a3bb-1c31-447b-b3d0-fdae3c6e4346)
![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/107404774/00e7dd0f-286d-4333-8a47-07825e022875)

**추가 **</br>

**Comment by getCurrentThread** [comment]
#244 로 현재 해결 중입니다. 익스텐션 검토 완료 후 24시간 후에 코멘트 닫도록 하겠습니다.

**Comment by getCurrentThread** [comment]
@lhseunge 어제 오후 9시 44분에 배포 완료되었습니다. 
업데이트 확인해보시고 문제 사항이 있으시면 말씀해주시기 바랍니다.

추가사항 없으시면 24시간 후에 이슈 닫도록 하겠습니다.

**Comment by lhseunge** [comment]
@getCurrentThread 
크롬 확장프로그램 업데이트 후 프로그래머스 문제 제출을 시도하였는데, 이번엔 푸시가 되지 않습니다. 

저장소는 기본 private에서 public으로 변경하였고, 확장프로그램과 저장소 unlink 후 재연결 이후 시도하여도 동일한 상태입니다.

![스크린샷 2024-02-20 오후 8 14 01](https://github.com/BaekjoonHub/BaekjoonHub/assets/107404774/2fe6eea2-7059-40d2-9f0a-85cc2be22567)
![스크린샷 2024-02-20 오후 8 09 44](https://github.com/BaekjoonHub/BaekjoonHub/assets/107404774/ebe0f86b-20cb-4116-8f31-8a1b70132a82)
![스크린샷 2024-02-20 오후 8 16 12](https://github.com/BaekjoonHub/BaekjoonHub/assets/107404774/08dfd594-cdf3-4804-8df8-9f051aef2eed)

**Comment by getCurrentThread** [comment]
@lhseunge 오늘 오후 6시 일자로 배포 완료되었습니다.
업데이트 확인해보시고 문제 사항이 있으시면 말씀해주시기 바랍니다.

추가사항 없으시면 24시간 후에 이슈 닫도록 하겠습니다.
