### ISSUE TITLE
백준 허브 미동작 건

### ISSUE THREAD

**Issue by lejehwan** [BaekjoonHub/BaekjoonHub#249]
**버그를 설명해주세요**</br>

백준 허브가 동작하지 않습니다.(아이콘이 표시되지 않으며, 업로드가 되지 않는 버그)

**재현 방법을 기술해주세요**</br>

저의 경우, 2월 20일 프로그래머스의 [기능개발]  문제를 푼 뒤 백준허브가 동작하는 것을 확인하였습니다.
그러나 2월 21일 같은 플랫폼의 [올바른 괄호] 문제를 푼 뒤 백준허브가 동작하지 않았습니다.
또한 전날의 동일한 문제를 재 제출 한 뒤에도 백준허브가 동작하지 않았습니다.

**스크린샷**</br>

![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/70786235/4cf4a0b8-9b46-4d49-9e19-7720806cc7a0)

**추가 **</br>

**Comment by Yimkeul** [comment]
저도 동일한 현상을 겪고 있습니다.
2월 21일 프로그래머스에서 해결한 문제가 안올라갑니다

**Comment by kmh5038** [comment]
저도 동일한 현상이 나타났습니다

**Comment by ChoiWoosung2194** [comment]
저도 동일한 현상이에요. 해결 방안이 있을까요?

**Comment by wlgns5518** [comment]
동일한 현상을 겪고있습니다

**Comment by dlwogus0128** [comment]
동일한 문제가 발생합니다.

**Comment by getCurrentThread** [comment]
#247 으로 오류 확인하였고, 현재 익스텐션 검토 과정 중에 있습니다.

**Comment by jeongho218** [comment]
동일한 현상이고, 개발자도구에서 보니 첨부 사진과 같이 에러 메세지가 나오고 있습니다. 
![캡처](https://github.com/BaekjoonHub/BaekjoonHub/assets/82637024/d7020855-c348-462e-965b-d2b803a60a1f)

**Comment by leesfact** [comment]
<img width="597" alt="image" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/121993153/0882a7fb-ba0b-4889-8da3-68cd614df4be">

저도 계속 업로드가 안돼서 확인해보니 동일 증상 확인하였습니다.

**Comment by Jiseon94** [comment]
저도 갑자기 업로드가 안되는 현상이 나타났습니다

**Comment by new-ying** [comment]
저는 당일 2.21 설치했는데 어쩐지 같은 이슈로 업로드 체크 미활성, 작동되지 않았던거같아요.

**Comment by jaeyeongs** [comment]
저도 마찬가지로 업로드가 되지 않습니다.

**Comment by OranGeShine01** [comment]
저도 어제부터 프로그래머스 같은현상 확인했습니다. 백준은 잘 됩니다.
