### ISSUE TITLE
알고리즘 분류 기능도 추가해주세요. 다시 복습할 때 알고리즘 카테고리가 정돈 되어 있으면 보기 편할 것 같아요

### ISSUE THREAD

**Issue by getbravelee** [BaekjoonHub/BaekjoonHub#253]
**해당 기능이 어떤 문제를 개선하나요?**</br>

**제안하고 싶은 기능을 설명해주세요**</br>

**직접 PR 여부**</br>

**Comment by getbravelee** [comment]
readme.md 에 말고 커밋내용에 있으면 좋을 것 같아요.. 근데 그러면 너무 길어질려나요

**Comment by getCurrentThread** [comment]
#106 기능과 중복됩니다.
