### ISSUE TITLE
커밋 전 성능 검사가 이상한 것 같습니다. 

### ISSUE THREAD

**Issue by lhseunge** [BaekjoonHub/BaekjoonHub#258]
**버그를 설명해주세요**</br>

백준허브 문서의 커밋 전 성능 비교 함수인데, 실행 시간 기준으로 우선 비교를 하는 것으로 알고 있지만, 실행 시간이 더 느린 답변 제출 시 커밋이 진행됩니다. 

```
function compareSubmission(a, b) {
	return a.runtime === b.runtime
           	? a.memory === b.memory
                 ? a.codeLength === b.codeLength
                      ? -(a.submissionId - b.submissionId)
                      : a.codeLength - b.codeLength
                 : a.memory - b.memory
            : a.runtime - b.runtime;
}
```

**재현 방법을 기술해주세요**</br>

맥os 
1.2.0
프로그래머스 
[문제](https://school.programmers.co.kr/learn/courses/30/lessons/181864
)

**스크린샷**</br>

![스크린샷 2024-03-10 오전 12 23 07](https://github.com/BaekjoonHub/BaekjoonHub/assets/107404774/0ac8b980-2c69-4a35-bd09-b1e13139029c)

**추가 **</br>

항상 유용하게 사용하고 있습니다. 감사합니다.

**Comment by getCurrentThread** [comment]
안녕하세요. 프로그래머스의 경우에는 제출 페이지가 별도로 없기 때문에 
평가할 대상이 없으므로 제출 시마다 갱신이 되는 점. 양해 부탁드리겠습니다.

해당 부분을 로컬 스토리지를 사용하여 자체 저장하고 이를 비교 대상으로 하여금 처리가 가능하나, 
실용적이거나 유용한 점이 없으므로 추가 구현되지 않았습니다.
