### ISSUE TITLE
웨일 확장앱 등록

### ISSUE THREAD

**Issue by moong23** [BaekjoonHub/BaekjoonHub#259]
**해당 기능이 어떤 문제를 개선하나요?**</br>

웨일 브라우저에서 백준허브 사용이 가능하도록 브라우저에 백준허브 확장앱 등록을 부탁드립니다

**제안하고 싶은 기능을 설명해주세요**</br>

웨일 브라우저를 위한 익스텐션(확장앱) 등록을 부탁드립니다.
웨일 브라우저에서 기존의 코드를 (거의)수정하지 않고 업로드 할 수 있습니다.

**직접 PR 여부**</br>

NO

**Comment by moong23** [comment]
https://store.whale.naver.com/extensions/new

**Comment by getCurrentThread** [comment]
안녕하세요. 백준허브 메인컨트리뷰터입니다.
현재 요청하신 백준허브의 웨일 스토어 검토를 진행중에 있습니다.
사용 도중 발생하는 오류의 경우가 있는 경우 추가로 코멘트 달아주시면 감사하겠습니다 :)

**Comment by getCurrentThread** [comment]
https://store.whale.naver.com/detail/kadlmokibfgmeafeeaedmfognkkbhaim 등록완료

**Comment by moong23** [comment]
감사합니다!
이슈 해결되었으니 해당 issue close하겠습니다 👍
