### ISSUE TITLE
문제 폴더를 삭제하고 다시 제출한 경우 push가 되지 않습니다.

### ISSUE THREAD

**Issue by don9m1n** [BaekjoonHub/BaekjoonHub#261]
<img width="349" alt="image" src="https://github.com/BaekjoonHub/BaekjoonHub/assets/61447654/8ec0335a-a395-4589-83d7-087afbeda566">

초록 체크 표시는 나오는데 깃허브에 올라오지가 않네요

**Comment by getCurrentThread** [comment]
안녕하세요. 이슈 남겨주셔서 감사합니다. 
우선, 현업에 의해 이슈 확인이 늦은 점 미리 양해를 구합니다.

백준허브는 기존의 사용자가 업로드를 한 내역을 기준으로 
그 파일의 해쉬값을 localstorage에 저장하여 활용하고 있습니다.

그 내역과 동일한 파일을 커밋을 하지 않도록 
중복 체크를 내부적으로 진행하고 있습니다.

되돌아가서 제시해주신 이슈 내용으로 문제 폴더를 
삭제하고 다시 제출하셨다고 문의를 남겨주셨습니다만,
이 경우는 백준허브에서 고려되지 않은 상황입니다.

버전 관리를 위한 행위가 아닌, 커밋 수를 늘리기 위한 행위로 악의적인 사용이 가능할 것으로 보여
이 문제에 대해서는 수정이나 예외 처리가 어려울 것으로 보여집니다.

추가적인 조치방안이나 직접적인 커밋을 진행해보실 의향이 있으시다면 적극 반영하도록 하겠습니다.

추가 피드 없으시면, 이슈 24시간 후에 닫도록 하겠습니다.

**Comment by don9m1n** [comment]
> 안녕하세요. 이슈 남겨주셔서 감사합니다. 우선, 현업에 의해 이슈 확인이 늦은 점 미리 양해를 구합니다.
> 
> 백준허브는 기존의 사용자가 업로드를 한 내역을 기준으로 그 파일의 해쉬값을 localstorage에 저장하여 활용하고 있습니다.
> 
> 그 내역과 동일한 파일을 커밋을 하지 않도록 중복 체크를 내부적으로 진행하고 있습니다.
> 
> 되돌아가서 제시해주신 이슈 내용으로 문제 폴더를 삭제하고 다시 제출하셨다고 문의를 남겨주셨습니다만, 이 경우는 백준허브에서 고려되지 않은 상황입니다.
> 
> 버전 관리를 위한 행위가 아닌, 커밋 수를 늘리기 위한 행위로 악의적인 사용이 가능할 것으로 보여 이 문제에 대해서는 수정이나 예외 처리가 어려울 것으로 보여집니다.
> 
> 추가적인 조치방안이나 직접적인 커밋을 진행해보실 의향이 있으시다면 적극 반영하도록 하겠습니다.
> 
> 추가 피드 없으시면, 이슈 24시간 후에 닫도록 하겠습니다.

안녕하세요! 답변 감사합니다
백준 허브 재설치 후 해결되었습니다. 이슈 닫아주시면 감사하겠습니다~
