### ISSUE TITLE
백준에서 푼 문제만 커밋되지 않습니다.

### ISSUE THREAD

**Issue by ih9511** [BaekjoonHub/BaekjoonHub#263]
**버그를 설명해주세요**</br>

먼저 좋은 프로그램 제공해주심에 감사의 말씀 드립니다.
현재 환경은 다음과 같습니다.
1. 개인 노트북을 통하여 최초 백준허브 extension 설치 및 깃헙 연동 후 다수의 프로그래머스 문제 커밋. (현재 제 레포에 프로그래머스 폴더가 있고 하위에 난이도에 따른 폴더들이 존재하는 상태입니다.)
2. 추가적으로, 데스크탑을 통해 동일한 레포로 extension 설정 완료. (해당 데스크탑에서 테스트해본 결과, 프로그래머스는 잘 올라가지만, 백준은 올라가지 않습니다.)

**재현 방법을 기술해주세요**</br>

OS: Windows 10
익스텐션 버전: 백준허브 v1.2.0
플랫폼: 백준
문제 종류: 일반 문제
문제: 백준 문제 전체 다

**스크린샷**</br>

**추가 **</br>

**Comment by medAndro** [comment]
현재 일반적인 문제 제출시 저는 정상적으로 작동중 입니다
백준의 각 문제별 '내 제출' 탭에서 '맞았습니다!!' 옆에 아무런 반응이 없으신 건가요?

**Comment by ih9511** [comment]
> 현재 일반적인 문제 제출시 저는 정상적으로 작동중 입니다 백준의 각 문제별 '내 제출' 탭에서 '맞았습니다!!' 옆에 아무런 반응이 없으신 건가요?

우선 원래 노트북에서 다시 시도해보았을 때 잘 작동합니다. 저녁에 집 데스크탑으로 다시 테스트 후에 코멘트 드리겠습니다. 답변 감사합니다.
