### ISSUE TITLE
업로드 동작 후 실패로 나옵니다

### ISSUE THREAD

**Issue by gyeongjae-ham** [BaekjoonHub/BaekjoonHub#265]
**버그를 설명해주세요**</br>

채점 후 업로드 시도하다가 실패합니다

**재현 방법을 기술해주세요**</br>

백준에서 채점 후 맞았습니다 출력 후 업로드 실패합니다

**스크린샷**</br>

[
![res](https://github.com/BaekjoonHub/BaekjoonHub/assets/75306311/11bbcf9a-87ff-4ba9-a0ac-5e17ddd45292)
![res2](https://github.com/BaekjoonHub/BaekjoonHub/assets/75306311/139f29d3-5758-4bca-aea5-51b69d9989f8)
](url)

**추가 **</br>

**Comment by eastsage** [comment]
동일한 오류 발생 중입니다!

**Comment by hoeeeeeh** [comment]
저도 현재 똑같은 현상입니다!
백준 문제였고, 스크린샷과 동일한 오류입니다!

**Comment by kwonhyunjeen** [comment]
[boj-extend](https://chromewebstore.google.com/detail/boj-extended/mfcaadoifdifdnigjmfbekjbhehibfel)의 에러로 보여서, 해당 확장 프로그램을 삭제하고 다시 제출하니 정상적으로 업로드 되었습니다!

**Comment by tjkpolisher** [comment]
동일한 오류 발생 중입니다.
boj-extend를 설치하지 않았는데도 문제가 발생합니다.
과거에 정상적으로 커밋된 문제를 다시 제출해서 테스트했는데 마찬가지로 커밋이 진행되지 않고 있습니다.

**Comment by hjgel** [comment]
저도 동일한 오류 발생중입니다 ㅜㅜ

**Comment by Bryan051** [comment]
![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/68111122/27969a78-c12a-488a-8f32-9a3f0c7d8385)
저는 cors 관련 에러일까요? 어제까지 괜찮았는데 오늘부터 갑자기 이러네요

**Comment by Bryan051** [comment]
> ![image](https://private-user-images.githubusercontent.com/68111122/338887057-27969a78-c12a-488a-8f32-9a3f0c7d8385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODQzNDcsIm5iZiI6MTcxODE4NDA0NywicGF0aCI6Ii82ODExMTEyMi8zMzg4ODcwNTctMjc5NjlhNzgtYzEyYS00ODhhLThmMzItOWEzZjBjN2Q4Mzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA5MjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NzE0YzdhYWE1ZGNjMTdjZTk2ZWY0NDU1OGE3MmIzMjQxNjgwMTNlNWZjNDFhMWE3YTY1ZjRlNjBmZmI3ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ywBDq5e-g5SL-Yu8hXx00-6YQOV9f6DNsGbqDYe3cFA) 저는 cors 관련 에러일까요? 어제까지 괜찮았는데 오늘부터 갑자기 이러네요

![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/68111122/5549e091-37f8-449e-846b-3fae713f863a)
CORS 정책 상 get (credential) 시
Access-Control-Allow-Origin 에 * 을 사용할 수 없는데
위 익스텐션으로 * 추가해서 해결했습니다. 다만 보안 문제가 있다고도 하고
토큰 문제일 수 도 있어 익스텐션 끄고 토큰 재발급을 받아봐야하겠습니다.

**Comment by Yoonyoung-han** [comment]
solved ac 사이트가 오늘 터졌었는데 이거랑 관련이 있는건가요? 이 사이트가 복구 되니까 또 잘 됩니다

**Comment by getCurrentThread** [comment]
solved.ac 사이트 이슈로 인하여 태그 정보를 못받아와 생기는 문제임을 확인하였습니대. 차후 동일 문제 시에 조치 예정입니다.

**Comment by getCurrentThread** [comment]
> ![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/68111122/27969a78-c12a-488a-8f32-9a3f0c7d8385)
> 저는 cors 관련 에러일까요? 어제까지 괜찮았는데 오늘부터 갑자기 이러네요

해당 오류는 구글 에드센스의 문제이며 백준허브는 광고를 포함하지 않습니다.

해당 오류 내역은 타 확장 프로그램, 백준 사이트에 문의해주시기 바랍니다.

**Comment by ja7811** [comment]
![image](https://github.com/BaekjoonHub/BaekjoonHub/assets/54016683/665efbf3-f9ab-41c5-8730-f0981fe00402)
저도 동일한 오류 발생합니다 😭
근데 콘솔에는 별다른 로그가 안 떠서 뭐가 문젠지 잘 모르겠네요

**Comment by gyeongjae-ham** [comment]
제가 생성한 이슈 내용은 solvec.ac 문제인 것으로 현재 잘 동작해서 이 이슈는 닫도록 하겠습니다
