### ISSUE TITLE
Edge 브라우저 환경에서 동작 안함

### ISSUE THREAD

**Issue by DownyBehind** [BaekjoonHub/BaekjoonHub#42]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**버그를 설명해주세요**</br>

현재 Edge 브라우저에서 확장프로그램으로 사용하려고 설치하였으나, 정상적인 동작이 되지 않습니다.
설명하신대로 BOJ 화면 내에 내 제출 화면으로 진입했으나, "맞았습니다!!" 라고 표시된 부분 뒤에 어떤 이미지도 생성되지 않습니다.

**Comment by flaxinger** [comment]
안녕하세요! 

백준허브를 사용해주셔서 감사합니다.

금일 현재 출시된 버전으로 Edge에서 테스팅을 진행하였으나 말씀하신 현상을 재현하지 못하였습니다.
[사용 설명서](https://velog.io/@flaxinger/%EB%B0%B1%EC%A4%80%ED%97%88%EB%B8%8C-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95)를 참고하여 레포지토리가 정상적으로 연결되었는지 확인 부탁드립니다.
혹 계속해서 문제가 해결되지 않는다면, 보다 구체적인 재현 방법을 알려주시면 참고하여 개선하겠습니다.

더불어 사용설명서에 기술되었듯 조만간 많은 버그가 개선된 1.0.2버전이 출시 예정이오니, 가급적 신규버전으로 이용 부탁드립니다.

이슈 신고해주신 점 진심으로 감사드립니다!

**Comment by DownyBehind** [comment]
안녕하세요. 답변 감사드립니다.

추가 내용 드립니다.

![연동결과](https://user-images.githubusercontent.com/41497254/149612447-45f8b5e6-ca88-452d-a4bf-187ec0f905f9.png)

위 사진과 같이 현재 제 깃허브 계정 내 레포와 연결되었다고 표시가 되었습니다.

이후에 BOJ에 가서 기 제출한 문제의 "내 제출" 탭을 갔지만 해당 내용이 제 레포에 업데이트 되지는 않았습니다. 

![내제출](https://user-images.githubusercontent.com/41497254/149612507-676b18fe-11a0-43a0-ab62-f02d7d0d3c4f.png)

이상입니다.

**Comment by flaxinger** [comment]
추가 설명 감사합니다!

Edge 최신 버전으로 이런 저런 테스팅 중이지만 아직 재현을 하지는 못했습니다.

혹시 개발자 툴의 콘솔에서 백준허브 관련 에러가 확인된다면 관련 댓글 부탁드립니다.

기존에 파싱 함수와 관련하여 (이번 버전에 보완된)버그를 확인한 적이 있으나, 이는 맥 환경에서 발견한 버그로 윈도우 환경이시라면 아직 파악하지 못한 문제가 있을 것으로 생각됩니다.

현재 상황에서는 다음 방법 외에 추천드릴 수 있는 방법이 없는 것 같습니다.

1. 레포 재연결 
2. 익스텐션 재설치 
3. 백준허브 신규 버전 사용 

추후 원인이 발견된다면 알려드리도록 하겠습니다.

불편을 드려 죄송합니다.

**Comment by DownyBehind** [comment]
안녕하세요. 답변 감사합니다. 

현재 맥북에서 다시 연동해서 진행하니 정상적으로 레포에 저장되는걸 확인했습니다.

감사합니다.

**Comment by getCurrentThread** [comment]
확인 완료했습니다. 
동일한 이슈가 있을 경우에 다시 해당 이슈 오픈하도록 하겠습니다.

**Comment by flaxinger** [comment]
정상 작동한다니 다행입니다.

추가로 조만간 배포될 새로운 버전에 많은 변화가 있어 현재 버전을 사용하고 계셨다면 배포 이후 이용에 불편이 있을 수 있습니다.
이에 따라 가급적 새로운 버전으로 배포가 된 이후에 사용하실 것을 권장드립니다.
배포일은 빠르면 16일로 예상하고 있습니다.

이슈 신고해주신 점 다시 한번 감사드립니다.

**Comment by flaxinger** [comment]
@DownyBehind 님 패치 완료되었습니다! Edge에서 사용하게 되신다면 작동 여부 부탁드립니다!

**Comment by DownyBehind** [comment]
@flaxinger 

안녕하세요. 금일 확인해보니 window 10 edge 브라우저에서도 정상적으로 동작합니다.

감사합니다!

**Comment by flaxinger** [comment]
오! 답변 감사합니다!
