### ISSUE TITLE
문제 제출 화면을 감지하지 못하는 이슈

### ISSUE THREAD

**Issue by zeromountain** [BaekjoonHub/BaekjoonHub#45]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**버그를 설명해주세요**</br>
- 백준 문제 제출 후, 문제 제출 화면을 감지하지 못합니다

@flaxinger 님 블로그 참고하며 차근 차근 따라 해봤지만, 지속적으로 문제 제출 화면을 감지하지 못해서 이슈 남기게 되었습니다,,
OS: macOS BigSur v.11.6
Browser: Chrome v.97.0.4692.99

**스크린샷**</br>
- 깃헙 링크 인증 화면
![스크린샷 2022-01-20 오후 9 22 28](https://user-images.githubusercontent.com/54147313/150339057-afcd4e87-9506-42f6-8be6-4da921b41f37.png)
- 백준 문제 제출 화면
![스크린샷 2022-01-20 오후 9 22 21](https://user-images.githubusercontent.com/54147313/150339101-fe021682-ab50-4247-823a-3a2d736e47f7.png)

**Comment by flaxinger** [comment]
추가로 혹시 리프레쉬를 해도 로딩이 안되는지 궁금합니다.
현재 제 로컬에서는 맞음 처리 되었을 때 자동으로 업로드되지 않으나 리프레쉬를 하면 인식되는 것으로 확인되었습니다.

**Comment by flaxinger** [comment]
원인 발견한 것 같습니다. #44 번  PR이 배포 이후에 적용되었는데 이 부분 반영하여 재배포하겠습니다. 불편을 드려 죄송합니다.

**Comment by zeromountain** [comment]
감사합니다 👍

**Comment by getCurrentThread** [comment]
핫픽스 v1.0.3 버전이 정상적으로 익스텐션에 업데이트 되었습니다.  
동일 문제가 있을 시에 해당 이슈 열어주시기 바랍니다. :)

이슈 닫습니다.
