### ISSUE TITLE
parsing 오류

### ISSUE THREAD

**Issue by zeromountain** [BaekjoonHub/BaekjoonHub#49]
**버그를 설명해주세요**</br>
- parsing할때 400번대 에러가 발생합니다

**재현 방법을 기술해주세요**</br>
- 문제 제출 시, 콘솔에 업로드 시작 안내가 출력되는데, parsing 과정에서 오류가 발생하는거 같습니다, 
- 404 페이지에서 "강의 슬라이드의 첨부 소스 코드가 404 에러가 뜨는 경우에는 링크를 복사/붙여넣기 해주세요."라는 안내가 있어서, 링크를 복붙해봤지만 같은 오류가 발생합니다.

**스크린샷**</br>
<img width="713" alt="스크린샷 2022-01-25 오전 1 27 31" src="https://user-images.githubusercontent.com/54147313/150823552-ec65de49-b347-47a1-bc75-2f0ffb3c36ff.png">

<img width="1065" alt="스크린샷 2022-01-25 오전 1 22 03" src="https://user-images.githubusercontent.com/54147313/150823507-789dc21a-711e-45b5-9b29-f4567bdbfad4.png">

**Comment by flaxinger** [comment]
제보 감사합니다. 
관련하여 테스팅을 진행해보겠습니다.
일회성 에러인지, 지속적인 에러인지 알려주신다면 도움이 될 것 같습니다.

**Comment by zeromountain** [comment]
지속적인 에러로 보여집니다 😂

**Comment by getCurrentThread** [comment]
@zeromountain 
현재 익스텐션 업데이트로 해결되었는지 확인이 필요합니다. 
동일한 에러가 발생하시는지 확인해주시면 감사하겠습니다 :)

**Comment by getCurrentThread** [comment]
현재 파싱 오류로 확인되는 커밋 목록
https://github.com/seongeun42/Baekjoon/commit/21e634a8b40dcd8efc91f044ccc89d422fad422d

**Comment by zeromountain** [comment]
@getCurrentThread 업로드 잘 됩니다 😃

**Comment by getCurrentThread** [comment]
아직 파싱 오류로 확인되는 커밋이 일부 있어서 이슈는 몇일 경과한 후에 닫겠습니다.
