### ISSUE TITLE
Third-Party

### ISSUE THREAD

**Issue by smartwe** [BaekjoonHub/BaekjoonHub#53]
이 확장프로그램을 써드 파티로 사용해도 되나요?

**Comment by flaxinger** [comment]
네 사용 가능합니다!
필수는 아니지만 저희 익스텐션 링크나 이름 남겨주신다면 감사드리겠습니다!

**Comment by smartwe** [comment]
https://github.com/smartwe/BOJ-App
아직 푸쉬하진 않았습니다
