### ISSUE TITLE
푼 적이 없는 코드가 올라가는 현상이 여전히 일어나는 것에 대하여

### ISSUE THREAD

**Issue by importjason** [BaekjoonHub/BaekjoonHub#54]
안녕하세요, 이전의 closed issue 에서 제목의 문제가 해결되었음을 확인했습니다.
(https://github.com/BaekjoonHub/BaekjoonHub/issues/18)

하지만 여전히 제 깃허브에 처음 보는 코드가 추가되는데, 아직 해당 현상이 일어날 수도 있는 것이 맞나요?

**Comment by getCurrentThread** [comment]
asap. 확인 후 회신 드리겠습니다.

**Comment by flaxinger** [comment]
안녕하세요?
불편을 드려 죄송합니다.
익스텐션이 url/화면 감지 후 동작하는데, 혹시 어떤 상황에서 일어나는 현상인지 알려주신다면 트러블슈팅에 도움이 될 것 같습니다!

**Comment by getCurrentThread** [comment]
@flaxinger @importjason 
문제를 제출한 즉시, 제출현황으로 넘어가게 된다면 
**가장 상위에 본인이 제출한 이력이 있는 상황이되므로** 현 로직을 무시하고 제출이 되네요. 

문제 확인했습니다. 
fix 후 merge 하겠습니다.

**Comment by getCurrentThread** [comment]
@importjason
혹시 백준 내의 제출 테이블을 변형하는 익스텐션을 활용중이시거나,
위에 언급된 상황이 아닌 상황에서 발생하였다면 추가 코멘트 부탁드립니다 :)

**Comment by importjason** [comment]
빠른 답변 감사드립니다.

@flaxinger 
아직 발생하는 상황이 특정되지 않아서, 여러 방법 시도 후 발견하는 대로 코멘트 드리겠습니다.

@getCurrentThread 
백준허브 외의 익스텐션은 따로 사용하고 있지 않습니다. 마찬가지로 상황이 특정되는 대로 코멘트 드리겠습니다.

감사합니다.

**Comment by importjason** [comment]
다소 늦은 시간이지만 규칙을 발견하여 남겨드립니다.

1. 문제 제출 직후, 정답 여부 확인하는 페이지에 머무를 때까지는 정상적으로 작동합니다. .py 파일이 추가되는 것을 확인했습니다.
2. 다만 제출현황으로 넘어가게 되면, .py 파일이 사라지고 .cc 파일이 남아있습니다.
**3. 해당 .cc 파일의 코드는, 제출현황 페이지에서 확인 가능한 가장 최근의 C++17 코드와 일치했습니다. (타인의 코드)**
4. 푼 적 없는 코드가 추가되는 경우, 오직 .cc 형식의 파일만 추가되는 상황입니다.

5. 추가적으로, 과거에 이미 푸쉬했던 백준 문제들은 다시 제출현황 페이지로 들어가도 오류가 발생하지 않았습니다. 첫 페이지에 제가 제출한 이력이 없기 때문일 수도 있겠다는 생각이 들었는데, 참고가 될까 싶어 말씀드립니다.

**Comment by getCurrentThread** [comment]
@importjason
이슈 확인했습니다. 
전체 제출 페이지를 보고 있을 때에는 기본 스케쥴러가 동작하지 않도록 로직을 수정해야할 것 같습니다.

확인 감사합니다. :)

**Comment by flaxinger** [comment]
저도 현상 확인했습니다. 빠른 시일 내에 패치하겠습니다. 감사합니다.
