### ISSUE TITLE
전체 코드 업로드 시에 undefined 폴더가 올라갑니다

### ISSUE THREAD

**Issue by getCurrentThread** [BaekjoonHub/BaekjoonHub#57]
> 커밋 검색 도중에 확인할 수 없는 에러가 있어, 다음과 같이 이슈에 기록해둡니다.

**버그를 설명해주세요**</br>
전체 코드 업로드로 undefined 폴더가 올라가는 오류
https://github.com/importjason/Baekjoon/commit/36d323eff340652f078e3d28c21a05f271736d74
![image](https://user-images.githubusercontent.com/31976959/151702552-9682de13-0be8-432a-9c2d-8ba7e6e031e9.png)

**Comment by flaxinger** [comment]
#58 로 해결되었으므로 닫겠습니다
