### ISSUE TITLE
과거 풀었던 문제를 개별로 추가할 때 기존의 폴더가 삭제되는 현상

### ISSUE THREAD

**Issue by importjason** [BaekjoonHub/BaekjoonHub#61]
과거 풀었던 문제를 '내 제출' 페이지에 들어가 하나씩 업로드하려다가 발견한 현상입니다.

1000, 1001, 1008번 코드를 순서대로 추가할 때,
1000, 1001 번 코드가 있는 상태에서 1008번을 추가하면
1000, 1001, 1008 코드가 레파지토리에 있어야 하지만 1001번이 없어지고 1000, 1008 만 남아있습니다.

어제오늘 이슈를 너무 많이 올리는 것 같아 마음이 안 좋네요..그냥 단순한 제 설정 문제이길 바라고 있습니다
항상 고맙게 사용하고 있습니다. 감사합니다

**Comment by importjason** [comment]
+ 1분정도 간격을 두고 업로드하니 정상적으로 작동하네요, 일정 시간 내에 코드 여러개를 업로드하려 하면 가장 마지막 것만 올라가는 것 같습니다.

**Comment by getCurrentThread** [comment]
https://github.com/importjason/Baekjoon/commit/bd87777bd0abc815a462755e447caae8fcb32f0b
https://github.com/importjason/Baekjoon/commit/ed5066239e9354f9a5dd37a81b3522bd244a4bc2

커밋 현황으로 문제 상황 확인했습니다.

이 부분은 GitHub API와 긴밀하게 연결되는 부분이 있어서 조금 시간이 걸릴 것 같습니다. 
양해 부탁드립니다 :)

**Comment by importjason** [comment]
네 그럼 부탁드립니다, 감사합니다 !

**Comment by getCurrentThread** [comment]
수정 후 익스텐션 배포 완료되었습니다.
