### ISSUE TITLE
'언어 제한' 태그가 붙은 문제는 푸시가 진행되지 않는 것 같습니다

### ISSUE THREAD

**Issue by SeongjinLee00** [BaekjoonHub/BaekjoonHub#62]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**버그를 설명해주세요**
'언어 제한' 태그가 붙은 문제는 푸시가 진행되지 않는 것 같습니다.

**재현 방법을 기술해주세요**
'언어 제한' 태그가 붙은 문제는 푸시가 진행되지 않는 것 같습니다.
예시로 저의 경우에는 15596, 15641번 문제만 진행되지 않습니다.

**추가 **
전체제출 업로드도 파싱 단계(-1/loading 출력)에서 8시간 이상 기다렸지만 진행이 안되는데, 이와 관련이 있는지는 모르겠습니다

**Comment by flaxinger** [comment]
아이고 죄송합니다.
버그 원인 확인했습니다.
다음 패치에 고치겠습니다.
더불어 전체제출 업로드 기능은 180개 문제 기준으로 약 30초가 소요되니 참고 부탁드립니다.

**Comment by getCurrentThread** [comment]
수정 후 익스텐션 배포 완료되었습니다.
