### ISSUE TITLE
Manifest v2 → v3로 마이그레이션 진행 제안

### ISSUE THREAD

**Issue by getCurrentThread** [BaekjoonHub/BaekjoonHub#64]
**해당 기능이 어떤 문제를 개선하나요?**</br>
크롬 익스텐션의 manifest v2에서 v3로 마이그레이션 진행 제안

**제안하고 싶은 기능을 설명해주세요**</br>
2022년부터 본격적으로 익스텐션에 대한 manifest 마이그레이션이 진행되어 
크롬에서 백준허브가 deprecate 되기전 매니패스트 마이그레이션을 적용하고자 합니다.
![image](https://user-images.githubusercontent.com/31976959/152488278-68cd8d37-eb54-4f6a-929f-c21556b921a7.png)

**추가 설명**</br>
마이그레이션 후, 테스트 및 익스텐션 작동 여부 및 게시 검토 통과를 확인하였습니다.
코드에 대한 편집사항은 다음 하단의 compare를 확인해주세요.
https://github.com/BaekjoonHub/BaekjoonHub/compare/v.1.0.6...getCurrentThread:v1.1.2

**직접 PR 여부**</br>
YES

**Comment by flaxinger** [comment]
진행하면 좋을 것 같습니다. PR 주시면 머지하겠습니다.
