### ISSUE TITLE
백준 익스텐션 검토를 위한 Nightly 버전을 추가 운영 제안

### ISSUE THREAD

**Issue by getCurrentThread** [BaekjoonHub/BaekjoonHub#65]
**해당 기능이 어떤 문제를 개선하나요?**</br>
현재 백준허브는 안정성을 위해서 항시 버전업을 하는데 어려움이 있는 상황입니다.
(예를 들어, 버그를 수정한 후에 실제 릴리즈 과정에 있어 추가 버그가 발견되는 등의 어려움을 겪고 있습니다.)

**제안하고 싶은 기능을 설명해주세요**</br>
차후 크롬 안정성에 따른 manifest v2에서 v3로 마이그레이션 작업을 진행하는데 있어서나
추가 기능에 대한 시험과 내부 구조 개편에 따른 각종 버그를 확인하기 위해서 
버전을 분리하여 익스텐션을 운영하는 것이 바람직해보입니다. 

> Nightly 버전은 하루하루 발생되는 이슈나 업데이트 사항이 있어 빌드되어 배포되는 버전입니다. 
> (현재 manifest v3의 익스텐션에서 사소한 마이너 버전업의 경우에는 5분 내에 빠른 검토를 해주는 것을 확인했습니다.)
> 
> 기존 익스텐션과 유저 사용 층이 갈라질 것을 대비하여 Nightly는 "미등록" 상태로 게시하는 것이 좋을 것 같습니다.

**추가 설명**</br>
Nightly 버전 익스텐션 활용 시나리오는 다음과 같습니다.
1. 유저의 Bug/Feature 이슈가 들어옴
2. 해당 이슈를 해결 또는 처리 후 Commit & Pull-Request
3. 해당 소스코드를 Nightly 버전으로 "미등록" 익스텐션 게시 및 검토
4. 해당 유저에게 Nightly 버전의 URL을 제공 및 에러사항이 없는지 확인
5. 안정성이 어느 정도 검토된 후 기존 백준허브 익스텐션에 업데이트 적용

**직접 PR 여부**</br>
현재 Owner이신 @flaxinger 님께서 Nightly 버전 운영에 어려움이 있으시다면은
그 부분은 제가 대리해도 문젠 없을 것 같습니다.

**Comment by flaxinger** [comment]
네 좋은 것 같습니다. 
그룹 퍼블리셔(Group Publisher) 계정을 만들면 그룹 소속 누구든 승인 신청 및 배포를 할 수 있다 하여 설정 후 초대장 보내드렸습니다.
시간 나실 때 확인 후 정상 작동하는지 확인 부탁드립니다.

**Comment by getCurrentThread** [comment]
확인 완료했습니다. 감사합니다.
