### ISSUE TITLE
타이머 만들어주세요.

### ISSUE THREAD

**Issue by getCurrentThread** [BaekjoonHub/BaekjoonHub#71]
**제안하고 싶은 기능을 설명해주세요**</br>
옆집 오픈소스를 보니까 탐스러운 문제 타이머가 있던데 백준허브도 있으면 좋을 것 같아요!

**추가 설명**</br>
<image src="https://github.com/joonas-yoon/boj-extended/raw/main/docs/images/screenshot-timer2.png" />
<image src="https://raw.githubusercontent.com/joonas-yoon/boj-extended/main/docs/images/screenshot-timer.png" />

**직접 PR 여부**</br>
NO

**Comment by flaxinger** [comment]
앜ㅋㅋㅋㅋㅋ 저도 생각하긴 했는데 뭔가 옆집 분들 아이디어 뺏아가는 기분이라 개선할 점이 있는지 조사해보겠습니다!

**Comment by ahajun96123** [comment]
현재 정답 중에 가장 빠르게 실행된 코드가 커밋되는데 가장 최근에 맞은 코드를 커밋할 수 있게 변경이나 옵션을 두면 좋겠습니다!

**Comment by getCurrentThread** [comment]
@ahajun96123 별도 이슈로 등록 바랍니다! :)
