### ISSUE TITLE
문제번호와 문제명 사이에 띄어쓰기 추가해주세요

### ISSUE THREAD

**Issue by chanmeee** [BaekjoonHub/BaekjoonHub#75]
경로 지정할 때 {문제번호}.{문제명}/{문제명}.{확장자}로 저장되는데, {문제번호}와 {문제명} 사이에 띄어쓰기를 1번 해주시면 가독성이 좋아질 거 같습니다. 

예를 들어, 현재 릴리즈된 버전으로는 2557.Hello World 라고 파일이 생성되는데, 2557. Hello World 로 띄어쓰기가 중간에 삽입되었으면 합니다. 편리한 구글 익스텐션 배포해주셔서 정말 감사드립니다. 👍

**Comment by flaxinger** [comment]
백준허브를 사용해주셔서 감사합니다. 
말씀하신 부분 다음 패치에 적용하도록 하겠습니다.
다만 기존에 푸시되었던 내역은 변경이 어려울 것으로 보여 양해를 구합니다.

**Comment by chanmeee** [comment]
네 의견 반영해주셔서 감사합니다.

좋은 서비스 만들어주셔서 다시 한번 감사드립니다.
