### ISSUE TITLE
이미지 깨짐 현상

### ISSUE THREAD

**Issue by pyapyapya** [BaekjoonHub/BaekjoonHub#88]
**README.md에서 이미지 깨짐 현상**</br>
REAMME.md에서 이미지 깨짐 현상이 발생합니다. 이는 백준에서 이미지를 불러 올때 상대 경로로 불러오기 때문에 깨지는 현상으로 확인됩니다.
따라서 `<img>` 태그 안에 있는 `src`에서 `https://acmicpc.net`을 포함한 경로로 포함하도록 적용하면 정상적으로 동작할 것으로 보입니다.

<img width="1032" alt="스크린샷 2022-02-28 오전 3 10 53" src="https://user-images.githubusercontent.com/42240862/155894841-c14a2f37-1964-485c-9d21-5fe1dba80793.png">

<img width="1364" alt="스크린샷 2022-02-28 오전 3 25 22" src="https://user-images.githubusercontent.com/42240862/155894885-02169ac4-92af-462f-95ab-8af0ebc8e1e7.png">

**Expected behavior**</br>
`JudgeOnline/upload/201007/down.png`
to
`https://acmicpc.net/JudgeOnline/upload/201007/down.png`

<img width="1053" alt="스크린샷 2022-02-28 오전 3 11 11" src="https://user-images.githubusercontent.com/42240862/155894892-ed9659c5-e02d-4842-ab2a-dd7822c81571.png">

**추가 **</br>
레퍼지터리 안에 있는 폴더 지정 경로가 가능한가요? 레퍼지터리만 경로로 잡히는 것 같아서요 ㅠ

**Comment by getCurrentThread** [comment]
@pyapyapya 
이슈 내용 커밋 [06623a7](https://github.com/BaekjoonHub/BaekjoonHub/pull/87/commits/06623a7baa5c080f2ca6c25998fb68877a0223fa) 으로 PR 완료하였습니다.

추가 사항으로 기재해주신 내용은 Feature Request 이슈로 분리하셔서 올려주세요! 😄  (본인 PR 여부 명시 필수!)
