### ISSUE TITLE
문제 파싱 단계 오류

### ISSUE THREAD

**Issue by flaxinger** [BaekjoonHub/BaekjoonHub#89]
**버그를 설명해주세요**</br>
문제 파싱 단계에 #76 번 이슈와 유사한 에러가 발생합니다. 
모든 사용자분들이 문제를 겪으실 것으로 예상되어 양해를 구합니다.
현재 해당 문제를 어떻게 조치할지 논의 중에 있으며,
문제 지문 파싱과 관련하여 앞으로도 계속해서 에러가 발생할 것으로 예상되어 현재는 해당 기능을 제거하는 것도 검토 중에 있습니다.
백준허브를 사용해주시는 모든 분들께 감사의 말씀을 드립니다.

**스크린샷**</br>
![image](https://user-images.githubusercontent.com/70012548/156277037-5ea33f0c-abf9-4049-8d88-5d6481ce8109.png)

![image](https://user-images.githubusercontent.com/70012548/156277088-86b0f604-a6a5-42d7-832b-0f0d6c5235b6.png)

**Comment by flaxinger** [comment]
@getCurrentThread 님의 #90 PR로 해결되었습니다.

**Comment by getCurrentThread** [comment]
금일 오후 3:55 분 백준허브 익스텐션 1.0.10버전 배포 확인하고 닫겠습니다.
