### ISSUE TITLE
업로드 실패가 뜹니다.

### ISSUE THREAD

**Issue by Nozzi2** [BaekjoonHub/BaekjoonHub#93]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**버그를 설명해주세요**</br>
크롬도 최신 업데이트하였고,
확장 프로그램또한 관리자모드를 통해 업그레이드 했습니다.
깃허브 연동도 이상없이 된 것을 확인했습니다.
문제를 제출하면 새탭이 열리고 업로드중이라고 뜨다가
에러코드가 나오면서 업로드 실패 메세지가 나옵니다.
혹시 제출했던 것을 다시 제출해서 그런가 싶어서 새로 계정을 파서 똑같이 제출해도 마찬가지입니다.
![image](https://user-images.githubusercontent.com/101002050/156893631-ca581338-f5bd-490d-9883-5473532e48ab.png)

너무 좋은 프로그램 만들어주셔서 감사합니다.
한번이라도 써보고싶어서 이렇게 요청드려봅니다.

**재현 방법을 기술해주세요**</br>

**Expected behavior**</br>

**스크린샷**</br>

**추가 **</br>

**Comment by flaxinger** [comment]
콘솔에 혹시 어디서 발생하는 문제인지 확인 부탁드려도 될까요?

**Comment by Nozzi2** [comment]
오늘도 문제풀고 제출했을때 이전에 보내드린 스크린샷과 똑같이 에러가 나서
직접 커밋하려고 제가 백준허브에 설정한 레포(Baekjoon)를 이클립스 패키지 경로에 설정했하고 커밋했습니다.
요청하신 질문 답변 남겨드리려고 같은 문제를 다시 제출을 눌렀더니 이번엔 에러가 나오지 않고 정상적으로 백준허브를 통해서 커밋되었습니다.
이상하다 싶어서 다른문제를 풀어서 제출하니 마찬가지로 정상적으로 커밋되었습니다.

계속 업로드 오류가 났었을 때는 해당 레포에 아무것도 올리지 않은 상태였습니다.
그리고 제 PC에 레포를 만들지 않았었구요.

지금은 잘 동작하고있으니 다행입니다만, 처음 계속 에러났었을땐 이유를 몰라서 조금 애먹었습니다..
만들어주신 프로그램 잘 사용하겠습니다. 감사합니다!

**Comment by getCurrentThread** [comment]
저 오류는 authorize 단계에서 제대로 처리가 되지 않을 때 나오는 오류입니다.
아마 github 내의 token 이 만료되었거나, 레포 연결이 제대로 되어 있지 않거나 하는 상황이었겠네요. :)
