### ISSUE TITLE
업로드 오류

### ISSUE THREAD

**Issue by jiwon79** [BaekjoonHub/BaekjoonHub#97]
**버그를 설명해주세요**</br>

문제를 풀고 결과창에서 업로드를 하는데 오류가 납니다.

**재현 방법을 기술해주세요**</br>

크롬을 사용하고 있고 백준 1003번 문제를 풀었습니다.

**스크린샷**</br>

![image](https://user-images.githubusercontent.com/59159410/159827560-63cd7d1b-8a67-4775-ac43-45e0488ab8ab.png)

**추가 **</br>

**Comment by getCurrentThread** [comment]
#93 과 동일한 Auth 오류라고 판단됩니다.
백준허브 익스텐션을 재설치하시거나, 백준허브의 Auth 과정을 다시 해주시기 바랍니다.
(자주 나오는 내용이라 해당 과정에 대한 예외조건은 추가하겠습니다.)

**Comment by getCurrentThread** [comment]
버그에 대한 예외처리와 안내 메시지를 추가하는 것으로 처리 조건 완료했습니다. 
익스텐션 업데이트 적용은 다음 기능 업데이트와 같이 이루어질 예정이니 양해부탁드립니다.

이슈 닫겠습니다.
